### ISSUE TITLE
train on Multi CPUs/GPUs,  FileExistsError: [Errno 17] File exists: './checkpoints/gan_pix2pix'

### ISSUE THREAD

**Issue by acoder-fin** [junyanz/pytorch-CycleGAN-and-pix2pix#1000]
I train the pix2pix model on 20 CPUs and 2 GPUs, and sometimes error occurs while sometimes does not.
The error message is:

```
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    opt = TrainOptions().parse()   # get training options
  File "cpGAN/options/base_options.py", line 124, in parse
    self.print_options(opt)
  File "cpGAN/options/base_options.py", line 108, in print_options
    util.mkdirs(expr_dir)
  File "cpGAN/util/util.py", line 93, in mkdirs
    mkdir(paths)
  File "cpGAN/util/util.py", line 103, in mkdir
    os.makedirs(path)
  File "/appl/soft/ai/miniconda3/envs/pytorch-1.4.0/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: './checkpoints/gan_pix2pix'
```

I wonder is this error caused by CPUs/GPUs?  Thank you!

**Comment by junyanz** [comment]
I think it is not related to CPU/GPU. Maybe you can try removing or renaming your directory `./checkpoints/gan_pix2pix`.

**Comment by acoder-fin** [comment]
The error is from the sbatch code for running the code on server. Solved now! 
Thank you!

**Comment by drunkprogrammer** [comment]
how to solve it?
