### ISSUE TITLE
Error when testing pix2pix with a single image

### ISSUE THREAD

**Issue by StuckinPhD** [junyanz/pytorch-CycleGAN-and-pix2pix#1018]
Hi,

I trained pix2pix with my own dataset which ran fine for 200 epochs and the visom results through training seem promising. I now want to test the model with a single test image (without the image pair format, just the A style image to convert to B style)

I placed that single image in its own folder and gave the following attributes, as is suggested to ``test.py``:

`--dataroot ./datasets/edge2face/single_test/ --name egde2face_pix2pix --model test --dataset_mode single`

But I get the following error:

> AttributeError: 'Sequential' object has no attribute 'model'

Here is the full output if that helps:

```
----------------- Options ---------------
             aspect_ratio: 1.0                           
               batch_size: 1                             
          checkpoints_dir: ./checkpoints                 
                crop_size: 256                           
                 dataroot: ./datasets/edge2face/single_test/	[default: None]
             dataset_mode: single                        
                direction: AtoB                          
          display_winsize: 256                           
                    epoch: latest                        
                     eval: False                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: False                         	[default: None]
                load_iter: 0                             	[default: 0]
                load_size: 256                           
         max_dataset_size: inf                           
                    model: test                          
             model_suffix:                               
               n_layers_D: 3                             
                     name: egde2face_pix2pix             	[default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: resnet_9blocks                
                      ngf: 64                            
               no_dropout: False                         
                  no_flip: False                         
                     norm: instance                      
                    ntest: inf                           
                 num_test: 50                            
              num_threads: 4                             
                output_nc: 3                             
                    phase: test                          
               preprocess: resize_and_crop               
              results_dir: ./results/                    
           serial_batches: False                         
                   suffix:                               
                  verbose: False                         
----------------- End -------------------
dataset [SingleDataset] was created
initialize network with normal
model [TestModel] was created
loading the model from ./checkpoints\egde2face_pix2pix\latest_net_G.pth
Traceback (most recent call last):
  File "C:/Users/PycharmProjects/pix2pix-cyclegan/test.py", line 47, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "C:\Users\PycharmProjects\pix2pix-cyclegan\models\base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "C:\Users\PycharmProjects\pix2pix-cyclegan\models\base_model.py", line 197, in load_networks
    self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))
  File "C:\Users\PycharmProjects\pix2pix-cyclegan\models\base_model.py", line 173, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "C:\Users\PycharmProjects\pix2pix-cyclegan\models\base_model.py", line 173, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'model'
```

Thanks

**Comment by junyanz** [comment]
You need to specify some flags such as `--netG` and `--norm`. See this [Q&A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#runtimeerror-errors-in-loading-state_dict-812-671461-296)

**Comment by StuckinPhD** [comment]
That made it work, thanks. I did not set any flags because I thought the default settings would be used for train and test. But I did not know that ``pix2pix`` rewrites the default values internally.

I want to recreate the edges2cat work but with faces, so I found a dataset of 23000 images of cropped faces ranges from babies to old.

I applied canny edge detection to extract edges and train. Below is the AB sample of this:

![26_1_2_20170116164549452 jpg chip](https://user-images.githubusercontent.com/44167893/81231310-df517c00-8fea-11ea-8143-969cf38f6b5d.jpg)

This was run for 200 epochs and the network seemed to be learning. Now when I give it a hand drawn test sample (one I draw in paint) :

![test_pix2pix_real](https://user-images.githubusercontent.com/44167893/81231433-0c059380-8feb-11ea-9b40-dba54e0624f7.png)

The network generated this:

![test_pix2pix_fake](https://user-images.githubusercontent.com/44167893/81231449-14f66500-8feb-11ea-9d75-038a3f21e6af.png)


But when I give it a unseen sample (not used during training)  from the same dataset:

![86_1_0_20170120134855602 jpg chip_real](https://user-images.githubusercontent.com/44167893/81231546-42dba980-8feb-11ea-9cd2-d1c5145c27fd.png)

It generates a somewhat acceptable result:

![86_1_0_20170120134855602 jpg chip_fake](https://user-images.githubusercontent.com/44167893/81231581-4d963e80-8feb-11ea-8843-82e968724e39.png)


What might be the reason for this?

Thank you

**Comment by junyanz** [comment]
There might be overfitting. You can do some flipping and cropping. 200 epochs might be too many for 23K images. Try some models with early epochs. There are two steps: 
1. first make sure that it works for your test images. 
2. make sure that your own drawing has the same stroke width and intensity as training images.
