### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.utils.hipify

### ISSUE THREAD

**Issue by 893205894** [junyanz/pytorch-CycleGAN-and-pix2pix#1048]
when i try to create the environment，it said No module named 'torch.utils.hipify',how can i deal with it?

**Comment by junyanz** [comment]
Not sure if it is related to this repo. We didn't use `hipify`.

**Comment by eburling** [comment]
I can second this. It has to do with the pip dependency on `git+https://github.com/pytorch/vision.git`.

Traceback:

```
(miniconda)[b@e p2p]$ conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/home/exacloud/tempwork/ChangLab/burlinge/miniconda/envs/sardana-p2p/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/exacloud/lustre1/ChangLab/burlinge/proj/SARDANA/p2p/condaenv.teozdspn.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/pytorch/vision.git (from -r ./p2p/condaenv.teozdspn.requirements.txt (line 2))
  Cloning https://github.com/pytorch/vision.git to /tmp/pip-req-build-6bpk1n6d
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-6bpk1n6d/setup.py", line 15, in <module>
        from torch.utils.hipify import hipify_python
    ImportError: No module named 'torch.utils.hipify'
```

**Comment by junyanz** [comment]
maybe  `pytorch` and `torchvision` version incompatibly?

**Comment by joslefaure** [comment]
`conda install torchvision` and `conda install pytorch` solved the problem in my case
