### ISSUE TITLE
Having problem in loading trained model stage

### ISSUE THREAD

**Issue by Orange199609** [junyanz/pytorch-CycleGAN-and-pix2pix#1066]
Hi!
Yesterday I trained my model with my own data for 300 epochs. However, when I want to reuse the model on test set, it came up with some error information

`Traceback (most recent call last):
  File "pix2pix/test.py", line 39, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/data/chengzihao/intern-programme/code/oneWeekPrice/pix2pix/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/data/chengzihao/intern-programme/code/oneWeekPrice/pix2pix/models/base_model.py", line 198, in load_networks
    net.load_state_dict(state_dict)
  File "/home/xiangwei/anaconda2/envs/tensorflow3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for UnetGenerator:
	Missing key(s) in state_dict: "model.model.1.model.2.weight", "model.model.1.model.2.bias", "model.model.1.model.2.running_mean", "model.model.1.model.2.running_var", "model.model.1.model.3.model.2.weight", "model.model.1.model.3.model.2.bias", "model.model.1.model.3.model.2.running_mean", "model.model.1.model.3.model.2.running_var", "model.model.1.model.3.model.3.model.2.weight", "model.model.1.model.3.model.3.model.2.bias", "model.model.1.model.3.model.3.model.2.running_mean", "model.model.1.model.3.model.3.model.2.running_var", "model.model.1.model.3.model.3.model.3.model.2.weight", "model.model.1.model.3.model.3.model.3.model.2.bias", "model.model.1.model.3.model.3.model.3.model.2.running_mean", "model.model.1.model.3.model.3.model.3.model.2.running_var", "model.model.1.model.3.model.3.model.3.model.3.model.2.weight", "model.model.1.model.3.model.3.model.3.model.3.model.2.bias", "model.model.1.model.3.model.3.model.3.model.3.model.2.running_mean", "model.model.1.model.3.model.3.model.3.model.3.model.2.running_var", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.2.weight", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.2.bias", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.2.running_mean", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.2.running_var", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.4.weight", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.4.bias", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.4.running_mean", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.4.running_var", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.6.weight", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.6.bias", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.6.running_mean", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.6.running_var", "model.model.1.model.3.model.3.model.3.model.3.model.6.weight", "model.model.1.model.3.model.3.model.3.model.3.model.6.bias", "model.model.1.model.3.model.3.model.3.model.3.model.6.running_mean", "model.model.1.model.3.model.3.model.3.model.3.model.6.running_var", "model.model.1.model.3.model.3.model.3.model.6.weight", "model.model.1.model.3.model.3.model.3.model.6.bias", "model.model.1.model.3.model.3.model.3.model.6.running_mean", "model.model.1.model.3.model.3.model.3.model.6.running_var", "model.model.1.model.3.model.3.model.6.weight", "model.model.1.model.3.model.3.model.6.bias", "model.model.1.model.3.model.3.model.6.running_mean", "model.model.1.model.3.model.3.model.6.running_var", "model.model.1.model.3.model.6.weight", "model.model.1.model.3.model.6.bias", "model.model.1.model.3.model.6.running_mean", "model.model.1.model.3.model.6.running_var", "model.model.1.model.6.weight", "model.model.1.model.6.bias", "model.model.1.model.6.running_mean", "model.model.1.model.6.running_var". 
	Unexpected key(s) in state_dict: "model.model.0.bias", "model.model.1.model.1.bias", "model.model.1.model.3.model.1.bias", "model.model.1.model.3.model.3.model.1.bias", "model.model.1.model.3.model.3.model.3.model.1.bias", "model.model.1.model.3.model.3.model.3.model.3.model.1.bias", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.1.bias", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.1.bias", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.3.bias", "model.model.1.model.3.model.3.model.3.model.3.model.3.model.5.bias", "model.model.1.model.3.model.3.model.3.model.3.model.5.bias", "model.model.1.model.3.model.3.model.3.model.5.bias", "model.model.1.model.3.model.3.model.5.bias", "model.model.1.model.3.model.5.bias", "model.model.1.model.5.bias". `

It seems like the dict stored in the model file cannot be read. The hyper parameters I used in the training step is as follows

> ----------------- Options ---------------

             aspect_ratio: 1.0                           
               batch_size: 1                             
                    beta1: 0.5                           
          checkpoints_dir: pix2pix/checkpoints           	[default: ./checkpoints]
           continue_train: True                          	[default: False]
                crop_size: 256                           
                 dataroot: pix2pix/datasets/0610-v2-fixPosition	[default: None]
             dataset_mode: aligned                       
                direction: AtoB                          
              display_env: main                          
             display_freq: 300                           	[default: 400]
               display_id: 1                             
            display_ncols: 4                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                           
                    epoch: 150                           	[default: latest]
              epoch_count: 151                           	[default: 1]
                 gan_mode: lsgan                         	[default: vanilla]
                  gpu_ids: 0,1                           	[default: 0]
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 1                             	[default: 3]
                  isTrain: True                          	[default: None]
                lambda_L1: 20.0                          	[default: 100.0]
                load_iter: 0                             	[default: 0]
                load_size: 286                           
                       lr: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: linear                        
         max_dataset_size: 3000                          	[default: inf]
                    model: pix2pix                       
                 n_epochs: 30                            	[default: 100]
           n_epochs_decay: 270                           	[default: 100]
               n_layers_D: 3                             
                     name: 0610v2                        	[default: experiment_name]
                      ndf: 32                            	[default: 64]
                     netD: basic                         
                     netG: unet_256                      
                      ngf: 64                            
               no_dropout: False                         
                  no_flip: True                          	[default: False]
                  no_html: False                         
                     norm: instance                      	[default: batch]
              num_threads: 3                             	[default: 4]
                output_nc: 1                             	[default: 3]
                    phase: train                         
                pool_size: 0                             
               preprocess: none                          	[default: resize_and_crop]
               print_freq: 300                           	[default: 100]
             save_by_iter: False                         
          save_epoch_freq: 2                             	[default: 5]
         save_latest_freq: 5000                          
           serial_batches: False                         
                   suffix:                               
         update_html_freq: 1000                          
                  verbose: False                         
----------------- End -------------------

Actually, I have reused the same code before and it is my first time to meet such problem. Could someone give me some advice?
Thanks a lot!

**Comment by Orange199609** [comment]
Fine! Rightly after I submitted this issue, the problem is solved. I am not sure but it seems like I double checked the hyper parameters I used in the test stage and made them completely the same with those in training stage. I don't know which hyper parameter is the key point but I strongly recommend that we have to keep them the same.
