### ISSUE TITLE
During  testing,can I just use one picture?

### ISSUE THREAD

**Issue by mrkind** [junyanz/pytorch-CycleGAN-and-pix2pix#1111]
I successfully trained my own pix2pix model.
However it seems that that the test script test.py only accepts a prepared dataset as input.Can I send a picture(ndarray or PILImage) to it and do not sacrifice prepairing a A-B dataset?

**Comment by junyanz** [comment]
It is possible. You can use the flag `--model test`.  See the [instruction](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-pix2pix). If you have issues, also see this [Q&A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#runtimeerror-errors-in-loading-state_dict-812-671461-296).

**Comment by mrkind** [comment]
Thanks author,I tried your suggestion ,it seems works,but I got the following Attribute error,how to solve it then?

loading the model from D:/vgan_pix2pix5/experiment_name\latest_net_G.pth
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers #在base_model.py中
  File "D:\360安全浏览器下载\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\models\base_model.py", line 94, in setup
    self.load_networks(load_suffix)
  File "D:\360安全浏览器下载\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\models\base_model.py", line 204, in load_networks
    self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))
  File "D:\360安全浏览器下载\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\models\base_model.py", line 180, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "D:\360安全浏览器下载\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\models\base_model.py", line 180, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'model'

**Comment by junyanz** [comment]
See this [Q&A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#runtimeerror-errors-in-loading-state_dict-812-671461-296).

**Comment by mrkind** [comment]
Thanks author!By overriding defaults,run successfully.

**Comment by junyanz** [comment]
Great!
