### ISSUE TITLE
Testing pix2pix model getting runtimeError: Sizes of tensors must match...

### ISSUE THREAD

**Issue by justkhant** [junyanz/pytorch-CycleGAN-and-pix2pix#1142]
I trained a pix2pix model using these settings `--model pix2pix --gpu_ids -1 --input_nc 1 --output_nc 1 --load_size 768 --crop_size 768 --preprocess crop`. And, i want to now test the model with --preprocess none so instead of cropping the full image is run through the model.  The command for testing I ran is this: `--model pix2pix --gpu_ids -1 --input_nc 1 --output_nc 1 --preprocess none`. 
But, I'm getting an error : 
```
The image size needs to be a multiple of 4. The loaded image size was (894, 1300), so it was adjusted to (896, 1300). This adjustment will be done to all images whose sizes are not multiples of 4

Traceback (most recent call last):
  File "test.py", line 63, in <module>
    model.test()           # run inference
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 105, in test
    self.forward()
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/pix2pix_model.py", line 88, in forward
    self.fake_B = self.netG(self.real_A)  # G(A)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 465, in forward
    return self.model(input)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 533, in forward
    return self.model(x)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 536, in forward
    print(self.model(x).size())
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 536, in forward
    print(self.model(x).size())
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 536, in forward
    print(self.model(x).size())
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 536, in forward
    print(self.model(x).size())
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 536, in forward
    print(self.model(x).size())
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 536, in forward
    print(self.model(x).size())
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/Users/kaungkhant/.pyenv/versions/3.8.5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/kaungkhant/Desktop/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 538, in forward
    return torch.cat([x, self.model(x)], 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Got 7 and 6 in dimension 3 (The offending index is 1)```

The testing works when I crop the test images to a multiple of 256. But, I want to be able to not have any preprocessing done on the inputs. 
Could you help me solve this issue?

**Comment by junyanz** [comment]
Unfortunately, U-Net only supports image sizes with a multiple of 256. If you train the model with `resnet_9blocks`, it can support image sizes with a multiple of 4.

**Comment by FlyDre** [comment]
hello, sir! Have you soled this problem? I faced this as well. Does the test folder pocess some pattern?
