### ISSUE TITLE
Training with --input_nc=1

### ISSUE THREAD

**Issue by soumyadeepg** [junyanz/pytorch-CycleGAN-and-pix2pix#116]
I am training with the following command

python train.py --dataroot ./datasets/casia_full_vis_hr_nir_hr --model cycle_gan --pool_size 50 --display_id 0 --batchSize 12 --display_winsize 128 --loadSize 130 --fineSize 128 --input_nc 1 --output_nc 1 --name 'load150fine128inp1out1_visHR_nirLR_FULL_CASIA' --which_direction 'BtoA' --norm 'batch' --display_winsize 128

I am getting the following error

Traceback (most recent call last):
  File "train.py", line 13, in <module>
    model = create_model(opt)
  File "/media/iiitd/New Volume1/soumyadeep_backup/pytorch-CycleGAN-and-pix2pix-master/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/media/iiitd/New Volume1/soumyadeep_backup/pytorch-CycleGAN-and-pix2pix-master/models/cycle_gan_model.py", line 31, in initialize
    opt.ngf, opt.which_model_netG, opt.norm, not opt.no_dropout, self.gpu_ids)
  File "/media/iiitd/New Volume1/soumyadeep_backup/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 123, in define_G
    init_weights(netG, init_type=init_type)
  File "/media/iiitd/New Volume1/soumyadeep_backup/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 73, in init_weights
    raise NotImplementedError('initialization method [%s] is not implemented' % init_type)
NotImplementedError: initialization method [[0]] is not implemented

@junyanz  Kindly Help !!

**Comment by junyanz** [comment]
It should be fixed. Let me know if it works for you.

**Comment by Eulsen** [comment]
Hi!
Thanks for implementing input_nc=1!
While the pix2pix implementation still works nicely,  for the Cycle Gan I am getting the same error as soumyadeepg above. (fresh git pull about an hour ago.) 
The error occurs also for input_nc=3, so maybe a new issue should be filed?
to be precise the error is:
(...)
cycle_gan
initialization method [xavier]
initialization method [xavier]
initialization method [[0]]
Traceback (most recent call last):
  File "train3.py", line 15, in <module>
    model = create_model(opt)
  File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\models.py", line 19, in create_model
    model.initialize(opt)
  File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\cycle_gan_model.py", line 39, in initialize
    opt.n_layers_D, opt.norm, use_sigmoid, self.gpu_ids)
  File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 144, in define_D
    init_weights(netD, init_type=init_type)
  File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 73, in init_weights
    raise NotImplementedError('initialization method [%s] is not implemented' % init_type)
NotImplementedError: initialization method [[0]] is not implemented

To me, it seems, as if something goes wrong with the initalization of the discriminator networks. However, I was not able to fix it myself.

Help would be much appreciated!!

**Comment by junyanz** [comment]
It should be fixed with the latest commit. Could you have a try again?

**Comment by Eulsen** [comment]
Hi!
Yes, I have tried it with the latest commit and I just tried again.
The pix2pix code works but the cycle gan code throws the error above also observed by soumyadeepg.
The cycle gan also throws the same error on the reference horse2zebra dataset and input_nc=3.
Before the latest commits the code ran smoothly.

If you do not mind, I will open a new issue, as, at least for me, the error is not related to the number of input color channels.

**Comment by junyanz** [comment]
Could you try the latest commit? I merged the patch made by @AndersAsa

**Comment by Eulsen** [comment]
Yup! now it works again!!

Thank you so much!

**Comment by rozentill** [comment]
I wonder if pix2pix now supports input_nc = 4 or 6? I mean if I can simply change the inputs to be 2 images and outputs 2 images also. Thanks.

**Comment by rozentill** [comment]
Thanks for your updates. But I still wonder if I can modify both the number of input and output channels, i.e. 6 channels for two images.
