### ISSUE TITLE
ValueError: empty range for randrange() (0,0, 0)

### ISSUE THREAD

**Issue by jongh222** [junyanz/pytorch-CycleGAN-and-pix2pix#1165]
python train.py --dataroot ./dataroot --gpu_ids -1

Traceback (most recent call last):
  File "train.py", line 44, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "C:\Users\Churi\Desktop\pytorch-CycleGAN-and-pix2pix-master\data\__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "C:\Users\Churi\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\Churi\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "C:\Users\Churi\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\Churi\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\Churi\Desktop\pytorch-CycleGAN-and-pix2pix-master\data\unaligned_dataset.py", line 55, in __getitem__
    index_B = random.randint(0, self.B_size - 1)
  File "C:\Users\Churi\anaconda3\lib\random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "C:\Users\Churi\anaconda3\lib\random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)

why?? My image is 1000x1000, load_size is 286, crop _size is 256...
Tried the Q&A and everything on the issue, but there is no progress...

**Comment by junyanz** [comment]
It seems that the code breaks in the following line. 
```python
index_B = random.randint(0, self.B_size - 1)
```
It indicates that self.B_size is 0. (the number of images in dataset B is 0). Have you checked if there are images in the training directory?
