### ISSUE TITLE
RuntimeError: ./checkpoints\experiment_name\latest_net_G.pth is a zip archive (did you mean to use torch.jit.load()?)

### ISSUE THREAD

**Issue by jongh222** [junyanz/pytorch-CycleGAN-and-pix2pix#1169]
----------------- End -------------------
dataset [AlignedDataset] was created
initialize network with normal
model [Pix2PixModel] was created
loading the model from ./checkpoints\experiment_name\latest_net_G.pth
Traceback (most recent call last):
  File "C:\Users\Churi\anaconda3\lib\tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: '_v2\nq\x03(('

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Churi\anaconda3\lib\tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "C:\Users\Churi\anaconda3\lib\tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "C:\Users\Churi\anaconda3\lib\tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "C:\Users\Churi\anaconda3\lib\tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Churi\anaconda3\lib\site-packages\torch\serialization.py", line 556, in _load
    return legacy_load(f)
  File "C:\Users\Churi\anaconda3\lib\site-packages\torch\serialization.py", line 467, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "C:\Users\Churi\anaconda3\lib\tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "C:\Users\Churi\anaconda3\lib\tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "C:\Users\Churi\anaconda3\lib\tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "C:\Users\Churi\anaconda3\lib\tarfile.py", line 2311, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 47, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "C:\Users\Churi\Desktop\여러가지\인공지능\pytorch-CycleGAN-and-pix2pix-master\models\base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "C:\Users\Churi\Desktop\여러가지\인공지능\pytorch-CycleGAN-and-pix2pix-master\models\base_model.py", line 192, in load_networks
    state_dict = torch.load(load_path, map_location=str(self.device))
  File "C:\Users\Churi\anaconda3\lib\site-packages\torch\serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Churi\anaconda3\lib\site-packages\torch\serialization.py", line 560, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: ./checkpoints\experiment_name\latest_net_G.pth is a zip archive (did you mean to use torch.jit.load()?)

I type "python test.py --dataroot ./dataroot --gpu_ids -1 --model pix2pix"

I renamed "latest_net_G_A.pth" to "latest_net_G.pth" in the file I trained and then ran it.

**Comment by JohanRaniseth** [comment]
I assume the test.py script is set up to search for "latest_net_G.pth" by default so renaming it might screw with things.

**Comment by jongh222** [comment]
> I assume the test.py script is set up to search for "latest_net_G.pth" by default so renaming it might screw with things.

If I don't change the name, the file doesn't exist.

**Comment by JohanRaniseth** [comment]
It does looks like you are trying to test something that doesn't exist.

You either have to train your own model:
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#pix2pix-traintest

Or you can download a pre-trained model and dataset:
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-pix2pix

Both of these will give you a /checkpoints/ directory with an experiment name and the "latest_net_G.pth" file that you are looking for and need for running test.py

**Comment by jongh222** [comment]
> It does looks like you are trying to test something that doesn't exist.
> 
> You either have to train your own model:
> https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#pix2pix-traintest
> 
> Or you can download a pre-trained model and dataset:
> https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-pix2pix
> 
> Both of these will give you a /checkpoints/ directory with an experiment name and the "latest_net_G.pth" file that you are looking for and need for running test.py

I already have a trained model. If you run the test with that file, the above error appears.

**Comment by JohanRaniseth** [comment]
Ah I see.

I tried researching a bit on google and it seems it could be due to wrong pytorch versions. Maybe one of these links can help you.

https://github.com/pytorch/pytorch/issues/43766

https://discuss.pytorch.org/t/problem-with-my-checkpoint-file-when-using-torch-load/92903/3

https://stackoverflow.com/questions/63406621/something-wrong-with-my-checkpoint-file-when-using-torch-load

**Comment by jongh222** [comment]
> Ah I see.
> 
> I tried researching a bit on google and it seems it could be due to wrong pytorch versions. Maybe one of these links can help you.
> 
> [pytorch/pytorch#43766](https://github.com/pytorch/pytorch/issues/43766)
> 
> https://discuss.pytorch.org/t/problem-with-my-checkpoint-file-when-using-torch-load/92903/3
> 
> https://stackoverflow.com/questions/63406621/something-wrong-with-my-checkpoint-file-when-using-torch-load

Normal files don't open with zip, but my files open. There seems to be a problem with training, but I don't know what's wrong...
