### ISSUE TITLE
About visdom

### ISSUE THREAD

**Issue by Youqi970124** [junyanz/pytorch-CycleGAN-and-pix2pix#1182]
I use pytorch-CycleGAN and pix2pix on ubuntu16.04
And I have installed my environment according to enviroment.yml.
But when I use train.py to training the cycleGAN model, I ran into some problems.

(pytorch-CycleGAN-and-pix2pix) youqi@youqi-System-Product-Name:~/anaconda3/pytorch-CycleGAN-and-pix2pix$ python -m visdom.server
Downloading scripts. It might take a while.
It's Alive!
INFO:root:Application Started
You can navigate to http://localhost:8097
ERROR:tornado.application:Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8097', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/youqi/anaconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.6/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/youqi/anaconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.6/site-packages/visdom/server.py", line 897, in get
    active_item=''
  File "/home/youqi/anaconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.6/site-packages/tornado/web.py", line 856, in render
    html = self.render_string(template_name, **kwargs)
  File "/home/youqi/anaconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.6/site-packages/tornado/web.py", line 1002, in render_string
    t = loader.load(template_name)
  File "/home/youqi/anaconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.6/site-packages/tornado/template.py", line 445, in load
    self.templates[name] = self._create_template(name)
  File "/home/youqi/anaconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.6/site-packages/tornado/template.py", line 476, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/youqi/anaconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.6/site-packages/visdom/static/index.html'
ERROR:root:ERROR: 500: {'exc_info': (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x7f5a6d0e4f08>)}
ERROR:tornado.access:500 GET / (::1) 2.10ms

And another question is when I open the http://localhost:8097
It is unable to connect to this website localhost refused to connect.
And I am pretty sure that the ubuntu network is connected.

I will be grateful for anyone's answer, it is very helpful to me.

**Comment by kw01sg** [comment]
Hi @Youqi970124 ,

Try pip removing visdom and conda installing the package [here](https://anaconda.org/conda-forge/visdom). 

You also might have to install a `jsonpatch` library.

**Comment by Youqi970124** [comment]
Dear @kw01sg ,
Very thank for your help.
I have been able to use the visdom  successfully.

Many thanks.

**Comment by SulinChi2021** [comment]
> Hi @Youqi970124 ,
> 
> Try pip removing visdom and conda installing the package [here](https://anaconda.org/conda-forge/visdom).
> 
> You also might have to install a `jsonpatch` library.

Many thanks!!!it is really helpful
