### ISSUE TITLE
AttributeError: Can't pickle local object 'get_transform.<locals>.<lambda>'

### ISSUE THREAD

**Issue by XinJiade** [junyanz/pytorch-CycleGAN-and-pix2pix#1197]
when I change the configuration of preprocess to "none" so that I can keep the size of my original picture，the problem occurs as following. Maybe the lambda in the transforms.Lambda should change.

Traceback (most recent call last):
  File "D:/WORKSPACE/py_temp/pytorch-CycleGAN-and-pix2pix-master/train.py", line 47, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "D:\WORKSPACE\py_temp\pytorch-CycleGAN-and-pix2pix-master\data\__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "D:\ProgramData\Anaconda3\envs\py36_7\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\ProgramData\Anaconda3\envs\py36_7\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "D:\ProgramData\Anaconda3\envs\py36_7\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\ProgramData\Anaconda3\envs\py36_7\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\py36_7\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\py36_7\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\ProgramData\Anaconda3\envs\py36_7\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_transform.<locals>.<lambda>'

**Comment by JunlinHan** [comment]
This is due to your environment. I would suggest you try setting num_threads to 0 and reinstall some packages (follow the requirements).

**Comment by KingOnTheStar** [comment]
Is there any solution? some I met the same problem.

**Comment by XinJiade** [comment]
Thanks  @JunlinHan, I’m sorry for not replying in time. For the solution , @KingOnTheStar, I had not continued to follow up on the issue  later. But I think the author's suggestion might be right.

**Comment by javadba** [comment]
I have also met this problem. The suggestion from JulinHan is too vague for knowing how to proceed.

**Comment by improgress** [comment]
change the "num_threads" to "0"
