### ISSUE TITLE
when I ran test.py of step1 on PyCharm,it occured an error.Here it is.

### ISSUE THREAD

**Issue by Psycho-Lv123** [junyanz/pytorch-CycleGAN-and-pix2pix#1205]
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    from util.visualizer import save_images
  File "C:\Users\Administrator\PycharmProjects\S2P\step1\util\visualizer.py", line 8, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize' from 'scipy.misc' (D:\softwares\anaconda\envs\Pytorch\lib\site-packages\scipy\misc\__init__.py)

**Comment by Amazingfanta** [comment]
you should try this :
pip install scipy==1.2.1
