### ISSUE TITLE
Cycle Gan throws "NotImplementedError: initialization method [[0]] is not implemented" after the latest commits

### ISSUE THREAD

**Issue by Eulsen** [junyanz/pytorch-CycleGAN-and-pix2pix#121]
Hi!
Thanks again for sharing this great piece of work!
While, after the latest commits the pix2pix implementation still works nicely, for the Cycle Gan I am now 
getting the following error:

(...)

cycle_gan
initialization method [xavier]
initialization method [xavier]
initialization method [[0]]
Traceback (most recent call last):
File "train3.py", line 15, in
model = create_model(opt)
File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\models.py", line 19, in create_model
model.initialize(opt)
File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\cycle_gan_model.py", line 39, in initialize
opt.n_layers_D, opt.norm, use_sigmoid, self.gpu_ids)
File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 144, in define_D
init_weights(netD, init_type=init_type)
File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 73, in init_weights
raise NotImplementedError('initialization method [%s] is not implemented' % init_type)
NotImplementedError: initialization method [[0]] is not implemented

To me, it seems, as if something goes wrong with the initalization of the discriminator networks. However, I was not able to fix it myself.

Can anyone help me? Anybody else experiencing the same problem?
Help would be much appreciated!!

**Comment by junyanz** [comment]
Sorry about that. I just merged the [patch](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/709d6153efdb4e8fe00c1285a3b55763946b32dc) made by @AndersAsa. and It should work.

**Comment by Eulsen** [comment]
Yup! now it works again!!

Thank you so much!
