### ISSUE TITLE
AssertionError: ./datasets/maps\trainA is not a valid directory

### ISSUE THREAD

**Issue by ChenShunHsu** [junyanz/pytorch-CycleGAN-and-pix2pix#1303]
i have error too, after i run this"python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan", the cmd show me "Traceback (most recent call last):
File "train.py", line 29, in
dataset = create_dataset(opt) # create a dataset given opt.dataset_mode and other options
File "C:\Users\USER\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data_init_.py", line 57, in create_dataset
data_loader = CustomDatasetDataLoader(opt)
File "C:\Users\USER\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data_init_.py", line 73, in init
self.dataset = dataset_class(opt)
File "C:\Users\USER\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\unaligned_dataset.py", line 29, in init
self.A_paths = sorted(make_dataset(self.dir_A, opt.max_dataset_size)) # load images from '/path/to/data/trainA'
File "C:\Users\USER\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\image_folder.py", line 25, in make_dataset
assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: ./datasets/maps\trainA is not a valid directory"

Can someone help me "AssertionError: ./datasets/maps\trainA is not a valid directory" means what?

**Comment by CN-cpu** [comment]
请问怎么解决的
