### ISSUE TITLE
python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan

### ISSUE THREAD

**Issue by Ss0222** [junyanz/pytorch-CycleGAN-and-pix2pix#1337]
When we train : python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan
An error occurred:
Traceback (most recent call last):
  File "train.py", line 33, in <module>
    model = create_model(opt)      # create a model given opt.model and other options
  File "/data/pytorch-CycleGAN-and-pix2pix-master/models/__init__.py", line 65, in create_model
    instance = model(opt)
  File "/data/pytorch-CycleGAN-and-pix2pix-master/models/cycle_gan_model.py", line 80, in __init__
    opt.n_layers_D, opt.norm, opt.init_type, opt.init_gain, self.gpu_ids)
  File "/data/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 196, in define_D
    net = NLayerDiscriminator(input_nc, ndf, n_layers=3, norm_layer=norm_layer)
  File "/data/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 584, in __init__
NameError: name 'model' is not defined
How to solve it ?

**Comment by taesungp** [comment]
Hello, this error is quite strange, because File "/data/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 584 is not inside `def __init__`. Did you make modifications to the code? Could you pull the latest code and re-run it?
