### ISSUE TITLE
test_video.py returns error when loading video 

### ISSUE THREAD

**Issue by Just-Gabe** [junyanz/pytorch-CycleGAN-and-pix2pix#1400]
I'm trying to load a video file as a videosource on a trained model, but everytime I try, it returns this:

Traceback (most recent call last):
  File "/content/realtime-pytorch-CycleGAN-and-pix2pix/test_video.py", line 83, in <module>
    model.set_input(data)  # unpack data from data loader
  File "/content/realtime-pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 109, in set_input
    self.real_B = input['B' if AtoB else 'A'].to(self.device)
KeyError: 'B'

I tried in Colab and in Desktop, Im using the following parameters:

!python /content/realtime-pytorch-CycleGAN-and-pix2pix/test_video.py --videosource /content/test.mp4 --name experiment1 --model cycle_gan

**Comment by silence-tang** [comment]
Hi, could you please share where did you get the realtime-pytorch-CycleGAN project? Thanks a lot.

**Comment by Just-Gabe** [comment]
Hi, I got it from this repo: https://github.com/Vinno97/realtime-pytorch-CycleGAN-and-pix2pix

Sorry for sending it here, I am aware that it is a fork project. I am getting the same error on some other tests I did, no idea why. Thats why I thought I could get some help here.

**Comment by silence-tang** [comment]
ok thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "junyanz/pytorch-CycleGAN-and-pix2pix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [junyanz/pytorch-CycleGAN-and-pix2pix] test_video.py returns error when loading video  (Issue #1400)





 
Hi, I got it from this repo: https://github.com/Vinno97/realtime-pytorch-CycleGAN-and-pix2pix
 
Sorry for sending it here, I am aware that it is a fork project. I am getting the same error on some other tests I did, no idea why. Thats why I thought I could get some help here.
