### ISSUE TITLE
Pix2Pix Input Inference Image Looks Different From the Original Inference Image

### ISSUE THREAD

**Issue by chokevin8** [junyanz/pytorch-CycleGAN-and-pix2pix#1572]
When running inference on Pix2Pix, in the results folder, you get real_A, real_B, and fake_B. The problem is that all of these images look different compared to the images that I've actually inputted into the dataroot to run inference. That's really weird, since my images are all 1024 x 1024 and the --preprocess option default (resize_and_crop) shouldn't change the size of the images or translate them. All of my images are 1024 x 1024, and I did "--direction AtoB --num_test 8 --load_size 1024 --crop_size 1024" when running inference. 

I can't show the images due to privacy reasons, but has anyone dealt with this weird problem during inference? I would understand if only fakeB looked different, but for some reason fakeA and realB looks different from the images that I loaded into dataroot to run inference. Thanks!

**Comment by arrrrr3186** [comment]
you can use  '--preprocess none'

**Comment by zhangjy328** [comment]
@arrrrr3186 
Hello. After I used the parameter '--preprocess none', the following error occurred. When I didn't use this parameter, the program could run normally. Why is that?
`python test.py --dataroot ./datasets/underwater_pix/test_AB --name underwater_pix2pix --model pix2pix --direction BtoA --preprocess none
`

Traceback (most recent call last):
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\test.py", line 74, in <module>
    model.test()           # run inference
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\base_model.py", line 105, in test
    self.forward()
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\pix2pix_model.py", line 88, in forward
    self.fake_B = self.netG(self.real_A)  # G(A)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\parallel\data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 466, in forward
    return self.model(input)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 534, in forward
    return self.model(x)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 536, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 536, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 536, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 536, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 536, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 536, in forward
    return torch.cat([x, self.model(x)], 1)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\models\enhance_models\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 536, in forward
    return torch.cat([x, self.model(x)], 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 3 but got size 2 for tensor number 1 in the list.

**Comment by ajanujaj** [comment]
@zhangjy328, could you please shape the of input tensors

**Comment by zhangjy328** [comment]
@ajanujaj Hello. I modified the images to 360×256 according to the tip "During test time, you can apply the model on 360x256 images with the flag --preprocess none." in the tips. When I ran it again, another error occurred. The error is:

File "D:\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (4 x 3). Kernel size: (4 x 4). Kernel size can't be greater than actual input size

I didn't encounter these problems when using the cycle model. For the pix model, If I don't input the --preprocess none parameter, it can run normally, but the obtained result is 256×256 in size. I want to get a rectangular result.
