### ISSUE TITLE
connection error?

### ISSUE THREAD

**Issue by DontGiveUpEasily** [junyanz/pytorch-CycleGAN-and-pix2pix#176]
I'm just running the cycle GAN example training code for maps, and have the following errors:

Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/cyclegan/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/username/anaconda3/envs/cyclegan/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/username/anaconda3/envs/cyclegan/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refusedConnectionRefusedError: [Errno 111] Connection refused

**Comment by ShaniGam** [comment]
add --display_id 0 to the train.py command

**Comment by zqdeepbluesky** [comment]
@ShaniGam It works ,thank you so much!
