### ISSUE TITLE
Have trouble connecting to port 8097

### ISSUE THREAD

**Issue by Lotayou** [junyanz/pytorch-CycleGAN-and-pix2pix#192]
Hi I have trouble connecting to the port 8097, and I guess maybe it's not easy for you to reproduce that issue... So I just wonder if there is a way to "switch off" the port connection module while still maintaining all the necessary training results? Thanks!

Here's the traceback error message, where I can't find out how this error is triggered. 
```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Anaconda3\envs\pytorch\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Anaconda3\envs\pytorch\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Anaconda3\envs\pytorch\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Anaconda3\envs\pytorch\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "D:\Anaconda3\envs\pytorch\lib\http\client.py", line 964, in send
    self.connect()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\connection.py", line 166, in connect
    conn = self._new_conn()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000021508F68240>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
```

**Comment by Lotayou** [comment]
Sorry my bad. I forget to turn on visdom.server. The problem is now solved.

**Comment by junyanz** [comment]
Cool. You can also disable the visdom with `--display_id -1`
