### ISSUE TITLE
Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by rainerkohlberger** [junyanz/pytorch-CycleGAN-and-pix2pix#207]
Hi,
trying to run test.py with the pretrained horse2zebra model and running into the following error. (train.py works). How to fix this? 
Thanks.

```
model [TestModel] was created
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    model.test()
  File "/media/dream/dev/pytorch-CycleGAN-and-pix2pix/models/test_model.py", line 37, in test
    self.fake_B = self.netG(self.real_A)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/dream/dev/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 255, in forward
    return self.model(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight'
```

**Comment by ShaniGam** [comment]
Try adding --gpu_ids -1 to your command

**Comment by rainerkohlberger** [comment]
Thanks that works. But then it's not using the GPU of course. Is there a way to do that?

**Comment by junyanz** [comment]
My bad. It should be fixed by the latest commit.

**Comment by rainerkohlberger** [comment]
Thanks, seems to work now.
