### ISSUE TITLE
RuntimeError: inconsistent tensor sizes

### ISSUE THREAD

**Issue by ShaniGam** [junyanz/pytorch-CycleGAN-and-pix2pix#208]
When I run the command:
`python train.py --dataroot ./datasets/facades --name facades  --model pix2pix --which_model_netG unet_256 --which_direction AtoB --lambda_A 100 --dataset_mode aligned --no_lsgan --norm batch --pool_size 0 --input_nc 1 --output_nc 1 --fineSize 80 --loadSize 80`

I get the error:
`Traceback (most recent call last):
  File "/home/shani/PycharmProjects/pix2pix/train.py", line 26, in <module>
    model.optimize_parameters()
  File "/home/shani/PycharmProjects/pix2pix/models/pix2pix_model.py", line 117, in optimize_parameters
    self.forward()
  File "/home/shani/PycharmProjects/pix2pix/models/pix2pix_model.py", line 73, in forward
    self.fake_B = self.netG.forward(self.real_A)
  File "/home/shani/PycharmProjects/pix2pix/models/networks.py", line 324, in forward
    return nn.parallel.data_parallel(self.model, input, self.gpu_ids)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 102, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/PycharmProjects/pix2pix/models/networks.py", line 380, in forward
    return self.model(x)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/PycharmProjects/pix2pix/models/networks.py", line 382, in forward
    return torch.cat([x, self.model(x)], 1)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/PycharmProjects/pix2pix/models/networks.py", line 382, in forward
    return torch.cat([x, self.model(x)], 1)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/PycharmProjects/pix2pix/models/networks.py", line 382, in forward
    return torch.cat([x, self.model(x)], 1)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/PycharmProjects/pix2pix/models/networks.py", line 382, in forward
    return torch.cat([x, self.model(x)], 1)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/PycharmProjects/pix2pix/models/networks.py", line 382, in forward
    return torch.cat([x, self.model(x)], 1)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/PycharmProjects/pix2pix/models/networks.py", line 382, in forward
    return torch.cat([x, self.model(x)], 1)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shani/PycharmProjects/pix2pix/models/networks.py", line 382, in forward
    return torch.cat([x, self.model(x)], 1)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 897, in cat
    return Concat.apply(dim, *iterable)
  File "/home/shani/anaconda2/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 317, in forward
    return torch.cat(inputs, dim)
RuntimeError: inconsistent tensor sizes at /opt/conda/conda-bld/pytorch_1511315759884/work/torch/lib/THC/generic/THCTensorMath.cu:141`

It also happens when I use another dataset with 80x80 images. It doesn't happen if I use the default parameters (256).
It also doesn't happen with CycleGAN, only when using pix2pix.

**Comment by ShaniGam** [comment]
It's because I tried using unet256 for 80 images...
