### ISSUE TITLE
AttributeError: 'CycleGANModel' object has no attribute 'real_A'

### ISSUE THREAD

**Issue by akshitamittel** [junyanz/pytorch-CycleGAN-and-pix2pix#248]
I have currently trained a model to one yosemite from summer to winter, using the commands given in the readme. I am currently testing the model on the dataset downloaded from the sh file and am running into the following error:

`python test.py --dataroot ./datasets/summer2winter_yosemite --name summer_cyclegan --model cycle_gan --phase test --no_dropout`

```
------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: ./datasets/summer2winter_yosemite/
dataset_mode: unaligned
display_id: 1
display_port: 8097
display_server: http://localhost
display_winsize: 256
fineSize: 256
gpu_ids: [0]
how_many: 50
init_type: normal
input_nc: 3
isTrain: False
loadSize: 286
max_dataset_size: inf
model: cycle_gan
nThreads: 4
n_layers_D: 3
name: summer_cyclegan
ndf: 64
ngf: 64
no_dropout: True
no_flip: False
norm: instance
ntest: inf
output_nc: 3
phase: test
resize_or_crop: resize_and_crop
results_dir: ./results/
serial_batches: False
suffix: 
verbose: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks
-------------- End ----------------
CustomDatasetDataLoader
dataset [UnalignedDataset] was created
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 11.378 M
[Network G_B] Total number of parameters : 11.378 M
-----------------------------------------------
model [CycleGANModel] was created
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    visuals = model.get_current_visuals()
  File "/home/amittel/Desktop/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 52, in get_current_visuals
    visual_ret[name] = getattr(self, name)
AttributeError: 'CycleGANModel' object has no attribute 'real_A'

```

**Comment by junyanz** [comment]
It was fixed by the latest [commit](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/commit/d7558eb269efdf181411e0b856df59647d916424). `git pull` and see if it works.

**Comment by akshitamittel** [comment]
Yes, it's working now. Thank you!
