### ISSUE TITLE
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by efang96** [junyanz/pytorch-CycleGAN-and-pix2pix#255]
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    model.test()
  File "/home/ubuntu/CS280_Project/pytorch-CycleGAN-and-pix2pix-master/models/test_model.py", line 40, in test
    self.fake_B = self.netG(self.real_A)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 71, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/CS280_Project/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 199, in forward
    return self.model(input)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR

I get this runtime error when running the following command on a custom dataset. I trained the model for 25 epochs and the results are saved. Any advice?

python test.py --dataroot datasets/cancer/testA --checkpoints_dir ./checkpoints/ --name cancer_cycle_gan --no_dropout --model test --dataset_mode single --loadSize 256

**Comment by efang96** [comment]
I just ran CycleGAN with a different dataset. I figured out the solution.. stopping and rebooting the EC2 instance solved it. 

Thanks :)
