### ISSUE TITLE
RuntimeError: Input type (CUDAFloatTensor) and weight type (CPUFloatTensor) should be the same

### ISSUE THREAD

**Issue by rharadgithub** [junyanz/pytorch-CycleGAN-and-pix2pix#259]
Dear sir, When I run the following script,
python train.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --which_model_netG unet_256 --which_direction BtoA --lambda_A 100 --dataset_mode aligned --no_lsgan --norm batch --pool_size 0,it shows the following error:

saving the model at the end of epoch 5, iters 2000
End of epoch 5 / 200 	 Time Taken: 61 sec
learning rate = 0.0002000
Traceback (most recent call last):
  File "train.py", line 31, in <module>
    model.optimize_parameters()
  File "/home/jlb/cyclejunyanz/pytorch-CycleGAN-and-pix2pix/models/pix2pix_model.py", line 110, in optimize_parameters
    self.forward()
  File "/home/jlb/cyclejunyanz/pytorch-CycleGAN-and-pix2pix/models/pix2pix_model.py", line 70, in forward
    self.fake_B = self.netG(self.real_A)
  File "/home/jlb/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jlb/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 71, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/habib/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jlb/cyclejunyanz/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 266, in forward
    return self.model(input)
  File "/home/jlb/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jlb/cyclejunyanz/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 320, in forward
    return self.model(x)
  File "/home/jlb/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jlb/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/jlb/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jlb/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/jlb/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Input type (CUDAFloatTensor) and weight type (CPUFloatTensor) should be the same

How can I solve this,Please help me.

**Comment by junyanz** [comment]
Which PyTorch version are you using? The current one only works with PyTorch 0.3. The 0.4 support will be added soon.

**Comment by rharadgithub** [comment]
@junyanz ,
I try with torch version=0.3.1.post2 and Anaconda3(python 3.6.4).I am looking forward to get next instruction.

**Comment by rharadgithub** [comment]
Dear @junyanz ,Now it is working by following issue #254: 
Weights are in CPU format

**Comment by junyanz** [comment]
Cool. Great!
