### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at c:\programdata\miniconda3\conda-bld\pytorch_1524546371102\work\aten\src\thc\generic/THCStorage.cu:58

### ISSUE THREAD

**Issue by ACUPSUN** [junyanz/pytorch-CycleGAN-and-pix2pix#280]
D:\Users\Administrator\jisuanji2\vision\pytorch-CycleGAN-and-pix2pix-master>python train.py --dataroot ./datasets/horse2zebra --name horse2zebra_cyclegan --model cycle_gan --no_dropout
------------ Options -------------
batchSize: 1
beta1: 0.5
checkpoints_dir: ./checkpoints
continue_train: False
dataroot: ./datasets/horse2zebra
dataset_mode: unaligned
display_freq: 400
display_id: 1
display_ncols: 4
display_port: 8097
display_server: http://localhost
display_winsize: 256
epoch_count: 1
fineSize: 256
gpu_ids: [0]
init_type: normal
input_nc: 3
isTrain: True
lambda_A: 10.0
lambda_B: 10.0
lambda_identity: 0.5
loadSize: 286
lr: 0.0002
lr_decay_iters: 50
lr_policy: lambda
max_dataset_size: inf
model: cycle_gan
nThreads: 4
n_layers_D: 3
name: horse2zebra_cyclegan
ndf: 64
ngf: 64
niter: 100
niter_decay: 100
no_dropout: True
no_flip: False
no_html: False
no_lsgan: False
norm: instance
output_nc: 3
phase: train
pool_size: 50
print_freq: 100
resize_or_crop: resize_and_crop
save_epoch_freq: 5
save_latest_freq: 5000
serial_batches: False
suffix:
update_html_freq: 1000
verbose: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks
-------------- End ----------------
CustomDatasetDataLoader
dataset [UnalignedDataset] was created
#training images = 1334
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
model [CycleGANModel] was created
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 11.378 M
[Network G_B] Total number of parameters : 11.378 M
[Network D_A] Total number of parameters : 2.765 M
[Network D_B] Total number of parameters : 2.765 M
-----------------------------------------------
create web directory ./checkpoints\horse2zebra_cyclegan\web...
THCudaCheck FAIL file=c:\programdata\miniconda3\conda-bld\pytorch_1524546371102\work\aten\src\thc\generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    model.optimize_parameters()
  File "D:\Users\Administrator\jisuanji2\vision\pytorch-CycleGAN-and-pix2pix-master\models\cycle_gan_model.py", line 134, in optimize_parameters
    self.backward_G()
  File "D:\Users\Administrator\jisuanji2\vision\pytorch-CycleGAN-and-pix2pix-master\models\cycle_gan_model.py", line 108, in backward_G
    self.idt_B = self.netG_B(self.real_A)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Users\Administrator\jisuanji2\vision\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 186, in forward
    return self.model(input)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 690, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: cuda runtime error (2) : out of memory at c:\programdata\miniconda3\conda-bld\pytorch_1524546371102\work\aten\src\thc\generic/THCStorage.cu:58

An error occurred while I was running the code ,then I deleted some of the train images.But there are still problems.like this 

D:\Users\Administrator\jisuanji2\vision\pytorch-CycleGAN-and-pix2pix-master>python train.py --dataroot ./datasets/horse2zebra --name horse2zebra_cyclegan --model cycle_gan --no_dropout
------------ Options -------------
batchSize: 1
beta1: 0.5
checkpoints_dir: ./checkpoints
continue_train: False
dataroot: ./datasets/horse2zebra
dataset_mode: unaligned
display_freq: 400
display_id: 1
display_ncols: 4
display_port: 8097
display_server: http://localhost
display_winsize: 256
epoch_count: 1
fineSize: 256
gpu_ids: [0]
init_type: normal
input_nc: 3
isTrain: True
lambda_A: 10.0
lambda_B: 10.0
lambda_identity: 0.5
loadSize: 286
lr: 0.0002
lr_decay_iters: 50
lr_policy: lambda
max_dataset_size: inf
model: cycle_gan
nThreads: 4
n_layers_D: 3
name: horse2zebra_cyclegan
ndf: 64
ngf: 64
niter: 100
niter_decay: 100
no_dropout: True
no_flip: False
no_html: False
no_lsgan: False
norm: instance
output_nc: 3
phase: train
pool_size: 50
print_freq: 100
resize_or_crop: resize_and_crop
save_epoch_freq: 5
save_latest_freq: 5000
serial_batches: False
suffix:
update_html_freq: 1000
verbose: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks
-------------- End ----------------
CustomDatasetDataLoader
dataset [UnalignedDataset] was created
#training images = 168
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
model [CycleGANModel] was created
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 11.378 M
[Network G_B] Total number of parameters : 11.378 M
[Network D_A] Total number of parameters : 2.765 M
[Network D_B] Total number of parameters : 2.765 M
-----------------------------------------------
create web directory ./checkpoints\horse2zebra_cyclegan\web...
THCudaCheck FAIL file=c:\programdata\miniconda3\conda-bld\pytorch_1524546371102\work\aten\src\thc\generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    model.optimize_parameters()
  File "D:\Users\Administrator\jisuanji2\vision\pytorch-CycleGAN-and-pix2pix-master\models\cycle_gan_model.py", line 134, in optimize_parameters
    self.backward_G()
  File "D:\Users\Administrator\jisuanji2\vision\pytorch-CycleGAN-and-pix2pix-master\models\cycle_gan_model.py", line 108, in backward_G
    self.idt_B = self.netG_B(self.real_A)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Users\Administrator\jisuanji2\vision\pytorch-CycleGAN-and-pix2pix-master\models\networks.py", line 186, in forward
    return self.model(input)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 690, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: cuda runtime error (2) : out of memory at c:\programdata\miniconda3\conda-bld\pytorch_1524546371102\work\aten\src\thc\generic/THCStorage.cu:58

i don't konw why it's happen?My GPU is 1050ti 4G. Can you help me?

**Comment by junyanz** [comment]
I think CycleGAN takes more than 4G for 256x256 images. Try 128x128 instead. Use `--which_model_netG resnet_128 --loadSize 143 --fineSize 128`
