### ISSUE TITLE
MacOS - RuntimeError: error executing torch_shm_manager

### ISSUE THREAD

**Issue by l2late** [junyanz/pytorch-CycleGAN-and-pix2pix#286]
Hello everyone,
First ever issue post for me. I'm not sure it's posted at the right place as this could also be a problem caused by PyTorch.

When running:

`python3 train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --no_dropout --gpu_ids -1
`
The program runs fine until after network initialization.
I get this error:

```
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 11.378 M
[Network G_B] Total number of parameters : 11.378 M
[Network D_A] Total number of parameters : 2.765 M
[Network D_B] Total number of parameters : 2.765 M
-----------------------------------------------
create web directory ./checkpoints/maps_cyclegan/web...
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    for i, data in enumerate(dataset):
  File "/Users/lucadelaat/Stack/Master/deep_learning/SuperResolution/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 51, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 135, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 135, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/utils/data/dataloader.py", line 113, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/storage.py", line 114, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: error executing torch_shm_manager at "/usr/local/lib/python3.6/site-packages/torch-0.4.0-py3.6-macosx-10.13-x86_64.egg/torch/lib/torch_shm_manager" at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/libshm/core.cpp:125

```

I run on MacOs High Sierra 10.13.4 with Python 3.6.5

**Comment by junyanz** [comment]
I am not sure if this issue is related to our repo. Are you able to run some simple PyTorch [demos](https://github.com/pytorch/examples)?
