### ISSUE TITLE
ZeroDivisionError while testing my trained model

### ISSUE THREAD

**Issue by Hunterwolf88** [junyanz/pytorch-CycleGAN-and-pix2pix#287]
Hello there,
I get this while trying to run rest.py

```
model [CycleGANModel] was created
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    for i, data in enumerate(dataset):
  File "/media/hunterwolf/DATA/_Coding/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 51, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/hunterwolf/anaconda3/envs/cyclegan/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/hunterwolf/anaconda3/envs/cyclegan/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ZeroDivisionError: Traceback (most recent call last):
  File "/home/hunterwolf/anaconda3/envs/cyclegan/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hunterwolf/anaconda3/envs/cyclegan/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/hunterwolf/DATA/_Coding/pytorch-CycleGAN-and-pix2pix/data/unaligned_dataset.py", line 27, in __getitem__
    index_B = index % self.B_size
ZeroDivisionError: integer division or modulo by zero
```

This is the script I use to run test.py:
`python test.py --dataroot ./datasets/model1 --name model1_cyclegan --model cycle_gan --dataset_mode unaligned --phase test --no_dropout`

I put my 2 test images in testA subfolder in the dataset folder, testB is empty.

**Comment by junyanz** [comment]
The code assumes that you have images in both test directory. If you only want to test one direction,  please use ‘--dataset_mode single’ and ‘--model test’ options.  You can find an example script in readme.

**Comment by Hunterwolf88** [comment]
thank you!
