### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at .. THCStorage.cu:66

### ISSUE THREAD

**Issue by doantientai** [junyanz/pytorch-CycleGAN-and-pix2pix#29]
I am trying to train the pix2pix model with the facedes database just like in the tutorial but getting Out Of Memory Error below.

My computer has GTX Titan 6GB. Is it enough?

`THCudaCheck FAIL file=/py/conda-bld/pytorch_1493676237139/work/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    model = create_model(opt)
  File "/users/taitien.doan/GANs/pix2pix/pytorch-CycleGAN-and-pix2pix/models/models.py", line 18, in create_model
    model.initialize(opt)
  File "/users/taitien.doan/GANs/pix2pix/pytorch-CycleGAN-and-pix2pix/models/pix2pix_model.py", line 26, in initialize
    opt.which_model_netG, opt.norm, opt.use_dropout, self.gpu_ids)
  File "/users/taitien.doan/GANs/pix2pix/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 46, in define_G
    netG.cuda(device_id=gpu_ids[0])
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 147, in cuda
    return self._apply(lambda t: t.cuda(device_id))
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 124, in _apply
    param.data = fn(param.data)
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/nn/modules/module.py", line 147, in <lambda>
    return self._apply(lambda t: t.cuda(device_id))
  File "/users/taitien.doan/anaconda3/envs/pix2pixlua/lib/python2.7/site-packages/torch/_utils.py", line 65, in _cuda
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (2) : out of memory at /py/conda-bld/pytorch_1493676237139/work/torch/lib/THC/generic/THCStorage.cu:66
`

**Comment by blitu12345** [comment]
@doantientai  have you solved this issue, if so could you help me ?

**Comment by doantientai** [comment]
Sorry I don't really remember but I try reduce the batch size.
