### ISSUE TITLE
when i start training cycle gan, i get the error:NameError: global name 'ConnectionError' is not defined

### ISSUE THREAD

**Issue by wjx2** [junyanz/pytorch-CycleGAN-and-pix2pix#305]
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    visualizer.plot_current_losses(epoch, float(epoch_iter) / dataset_size, opt, losses)
  File "/home/smartdsp/wangjx/Transfer_Learning/Detection/pytorch-CycleGAN-and-pix2pix-master/util/visualizer.py", line 152, in plot_current_losses
    except ConnectionError:
NameError: global name 'ConnectionError' is not defined

**Comment by davidwessman** [comment]
Try settings `--display_id -1`, this is a failing call to Visdom.

Check the `Visualization` part [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#trainingtest-details).
