### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused'

### ISSUE THREAD

**Issue by kebijuelun** [junyanz/pytorch-CycleGAN-and-pix2pix#345]
When I run the train.py file, I got this error, although I can fix this by add --display_id -1, I want to know how to connec to Visdom server.

ConnectionRefusedError: [Errno 111] Connection refused

Traceback (most recent call last):
  File "/home/liuweizhou/anaconda3/envs/pytorch0.41/lib/python3.6/site-packages/visdom/__init__.py", line 431, in _send
    data=json.dumps(msg),
  File "/home/liuweizhou/anaconda3/envs/pytorch0.41/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/liuweizhou/anaconda3/envs/pytorch0.41/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/liuweizhou/anaconda3/envs/pytorch0.41/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/liuweizhou/anaconda3/envs/pytorch0.41/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/liuweizhou/anaconda3/envs/pytorch0.41/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f197bddefd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by Homura2333** [comment]
Hello, how did you fix it?
