### ISSUE TITLE
Cuda runtime error (8) : invalid device function

### ISSUE THREAD

**Issue by HELIE86** [junyanz/pytorch-CycleGAN-and-pix2pix#352]
I was trying to reproduce this project with the instruction.and i’m used the Quadro 5000.Although the graphics card is old,I installed pyTorch and other packages as required in requirements. But the training, a program was terminates and the error was:

#training images = 258
pix2pix
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCTensorMath.cu line=15 error=8 : invalid device function
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    model = create_model(opt)
  File "/home/sky/pix2pix/pytorch-CycleGAN-and-pix2pix-master/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/home/sky/pix2pix/pytorch-CycleGAN-and-pix2pix-master/models/pix2pix_model.py", line 27, in initialize
    opt.which_model_netG, opt.norm, not opt.no_dropout, self.gpu_ids)
  File "/home/sky/pix2pix/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 51, in define_G
    netG.apply(weights_init)
  File "/home/sky/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 136, in apply
    module.apply(fn)
  File "/home/sky/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 136, in apply
    module.apply(fn)
  File "/home/sky/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 136, in apply
    module.apply(fn)
  [Previous line repeated 1 more times]
  File "/home/sky/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 137, in apply
    fn(self)
  File "/home/sky/pix2pix/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 18, in weights_init
    m.bias.data.fill_(0)
RuntimeError: cuda runtime error (8) : invalid device function at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:15

I am new to pyTorch, can you give me some advice on solving this problem? Thank you

**Comment by junyanz** [comment]
I am not sure if this is related to this repo. Would you be able to run some PyTorch [examples](https://github.com/pytorch/examples) on your machine?

**Comment by SsnL** [comment]
Your GPU is too old. PyTorch should have given you a warning. It is not supported anymore.
