### ISSUE TITLE
Some troubles

### ISSUE THREAD

**Issue by des1red** [junyanz/pytorch-CycleGAN-and-pix2pix#380]
Finally,i can run the train.py,but still with some trobles.
Q1: I use the CPU model,then i set gpu_ids -1.The results is 
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    data_loader = CreateDataLoader(opt)
  File "C:\Users\xiang\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\__init__.py", line 46, in CreateDataLoader
    data_loader.initialize(opt)
  File "C:\Users\xiang\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\__init__.py", line 58, in initialize
    self.dataset = create_dataset(opt)
  File "C:\Users\xiang\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\__init__.py", line 39, in create_dataset
    instance.initialize(opt)
  File "C:\Users\xiang\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\unaligned_dataset.py", line 19, in initialize
    self.A_paths = make_dataset(self.dir_A)
  File "C:\Users\xiang\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\image_folder.py", line 26, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: ./datasets/maps\trainA is not a valid directory

Q2:I use the default gpu_id 0 to run.and input 'command python -m visdom.server'.found there was nothing in 'http://localhost:8097',and there was only a opt.txt in '\checkpoints\maps_cyclegan' ,no somewhat HTML files.

Due to my poor English,I don't know if you can understand my problems.
Thanks.

**Comment by junyanz** [comment]
It seems that you haven't downloaded the dataset. Please run `bash ./datasets/download_cyclegan_dataset.sh maps` to get the dataset. Please ask the question in English so that others can also answer it.

**Comment by ChenShunHsu** [comment]
i have error too, after i run this"python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan", the cmd show me "Traceback (most recent call last):
  File "train.py", line 29, in <module>
    dataset = create_dataset(opt)  # create a dataset given opt.dataset_mode and other options
  File "C:\Users\USER\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\__init__.py", line 57, in create_dataset
    data_loader = CustomDatasetDataLoader(opt)
  File "C:\Users\USER\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\__init__.py", line 73, in __init__
    self.dataset = dataset_class(opt)
  File "C:\Users\USER\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\unaligned_dataset.py", line 29, in __init__
    self.A_paths = sorted(make_dataset(self.dir_A, opt.max_dataset_size))   # load images from '/path/to/data/trainA'
  File "C:\Users\USER\Downloads\pytorch-CycleGAN-and-pix2pix-master\pytorch-CycleGAN-and-pix2pix-master\data\image_folder.py", line 25, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: ./datasets/maps\trainA is not a valid directory"

Can someone help me "AssertionError: ./datasets/maps\trainA is not a valid directory" means what?

**Comment by junyanz** [comment]
It seems that you are using Windows. You probably need to fix the directory path (e.g.,  \ rather than / )
