### ISSUE TITLE
FineTuning using available pertained weights

### ISSUE THREAD

**Issue by parmidaatg** [junyanz/pytorch-CycleGAN-and-pix2pix#381]
Hi there, 

I am trying to finetune your winter2summer model since yesterday and every time the process crashes because a file is missing. Could you please help me through this on how I can make it work? 
for main part, I followed the procedure to put my winter images under " datasets/winter2summer_yosemite/trainA and .../trainB" 
I also downloaded the weights for winter2summer model and I use the following command: 
`python3 train.py --dataroot datasets/winter2summer_yosemite --name winter2summer_yosemite --model cycle_gan --continue_train`
during the training I was missing weights "./checkpoints/winter2summer_yosemit/latest_net_G_A.pth" so I just copied "./checkpoints/winter2summer_yosemit_pretrained/latest_net_G.pth" to the above file . 

I was then missing "./checkpoints/winter2summer_yosemit/latest_net_G_B.pth". So I downloaded "summer2winter" pretrained weights and I put them under the requested file. 

Now I am missing ""./checkpoints/winter2summer_yosemit/latest_net_D_A.pth"  and I am assuming that after this I might be missing ""./checkpoints/winter2summer_yosemit/latest_net_D_B.pth" 

Could you please let me know where I can get the complete set of requested weights for fine tuning or am I doing something wrong here? 

I would really appreciate your help. 

For more details, here is the error:
`Traceback (most recent call last):
  File "train.py", line 15, in <module>
    model.setup(opt)
  File "/app/models/base_model.py", line 43, in setup
    self.load_networks(opt.epoch)
  File "/app/models/base_model.py", line 129, in load_networks
    state_dict = torch.load(load_path, map_location=str(self.device))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/winter2summer_yosemite/latest_net_D_A.pth'`

**Comment by junyanz** [comment]
The current CycleGAN fine-tuning assumes that you have G_A, G_B, D_A, and D_B. Unfortunately, we currently only provide the generators as they can be used during test time. One quick hack that you can do is to only load the weights for G_A and G_B, but train D_A and D_B from scratch. We haven't tried that by ourselves and not sure about the results. You probably can do it by removing `D_A` and `D_B` from this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L39).

**Comment by junyanz** [comment]
The number of examples can be different.

**Comment by fishman2008** [comment]
> The current CycleGAN fine-tuning assumes that you have G_A, G_B, D_A, and D_B. Unfortunately, we currently only provide the generators as they can be used during test time. One quick hack that you can do is to only load the weights for G_A and G_B, but train D_A and D_B from scratch. We haven't tried that by ourselves and not sure about the results. You probably can do it by removing `D_A` and `D_B` from this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py#L39).

Regarding the fine-tuning, I have loaded the G and retrain the D. However, the performance does not make much difference. The starting learning rate is the same. I also tried to load both G and D and retrained them, no big difference as well. Any suggestions? Thanks.

**Comment by junyanz** [comment]
What is the purpose of fine-tuning? Fine-tuning on a different dataset? I think the released models are already well-trained on the original dataset, and fine-tuning might not help.

**Comment by fishman2008** [comment]
@junyanz Yes, that is the purpose. For instance, one dataset has a large number of pairs and another dataset has a small number of pairs. In this case, how can we fine-tune the model trained on a large dataset to get good results for the small dataset?

**Comment by junyanz** [comment]
I think loading D is not so important, as you can train D given a G, not vice versa.
