### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'display_winsize'

### ISSUE THREAD

**Issue by vin-ni** [junyanz/pytorch-CycleGAN-and-pix2pix#383]
I'm running the cycleGan test:
`python test.py --dataroot datasets/horse2zebra/testA --name horse2zebra_pretrained --model test`

but unfortunately get this error. (I read in another issue that this should already be fixed. What could it be?)
```
processing (0000)-th image... ['datasets/horse2zebra/testA/n02381460_1000.jpg']
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f17ec203c50>>
Traceback (most recent call last):
  File "/home/vinni/miniconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/vinni/miniconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/vinni/miniconda3/lib/python3.5/multiprocessing/queues.py", line 337, in get
    return ForkingPickler.loads(res)
  File "/home/vinni/miniconda3/lib/python3.5/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/vinni/miniconda3/lib/python3.5/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/vinni/miniconda3/lib/python3.5/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/vinni/miniconda3/lib/python3.5/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/home/vinni/miniconda3/lib/python3.5/multiprocessing/connection.py", line 737, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/vinni/miniconda3/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/vinni/miniconda3/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/vinni/miniconda3/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    save_images(webpage, visuals, img_path, aspect_ratio=opt.aspect_ratio, width=opt.display_winsize)
AttributeError: 'Namespace' object has no attribute 'display_winsize'

```
Could it be miniconda? I'm on ubuntu 18.04.

**Comment by parmidaatg** [comment]
I fixed it but replacing the opt.display_winsize into 256. the reason is that the display_winsize is part of the train options but  it is not part of test options. so the script cannot find it. The default value in train options is 256.

**Comment by vin-ni** [comment]
Ah this works! Thanks!
