### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'display_winsize'

### ISSUE THREAD

**Issue by tiaoqihaha** [junyanz/pytorch-CycleGAN-and-pix2pix#396]
When I want to test the model ,errors show like this:
processing (0000)-th image... ['./datasets/maps/testA/1000_A.jpg']
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f8410eabac8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 181, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 152, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    save_images(webpage, visuals, img_path, aspect_ratio=opt.aspect_ratio, width=opt.display_winsize)
AttributeError: 'Namespace' object has no attribute 'display_winsize'

As is showing above,there are some errors ,but I don't know whick is the fatal one?

**Comment by tiaoqihaha** [comment]
I solved the problem with adding an attribute "opt.display_winsize" in test.py

**Comment by junyanz** [comment]
Are you using the latest code? Which pytorch version are you using? display_winsize should have been defined in the base_options.py
