### ISSUE TITLE
undefined symbol: PySlice_Unpack

### ISSUE THREAD

**Issue by julien-arch** [junyanz/pytorch-CycleGAN-and-pix2pix#4]
Cool that you got it all to PyTorch!

When running python train.py --dataroot ./datasets/facades --name facades_cyclegan --model cycle_gan
I get:
Traceback (most recent call last):
  File "train.py", line 2, in <module>
    from options.train_options import TrainOptions
  File "/home/ubuntu/pytorch-CycleGAN-and-pix2pix/options/train_options.py", line 1, in <module>
    from .base_options import BaseOptions
  File "/home/ubuntu/pytorch-CycleGAN-and-pix2pix/options/base_options.py", line 3, in <module>
    from util import util
  File "/home/ubuntu/pytorch-CycleGAN-and-pix2pix/util/util.py", line 4, in <module>
    from PIL import Image
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: /home/ubuntu/miniconda3/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PySlice_Unpack

What versions are you using?

**Comment by julien-arch** [comment]
Fixed it by using Python 3.5, cuDNN 5.1, CUDA 8
