### ISSUE TITLE
line 32 at options/base_options.py, type of --load_iter should be "int" instead of "str"

### ISSUE THREAD

**Issue by akatsukimao** [junyanz/pytorch-CycleGAN-and-pix2pix#440]
Dear author,

I tried to apply the pretrained model(pix2pix) and I got a Error saying that

```
Traceback (most recent call last):                                                               
 File "test.py", line 20, in <module>                                                           
 File "~/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 42, in  load_suffix = 'iter_%d' % opt.load_iter if opt.load_iter > 0 else opt.epoch                  
TypeError: '>' not supported between instances of 'str' and 'int'  
```

I guessed that line 32 at options/base_options.py, type of --load_iter should be "int" instead of "str". After fixing that, my experiment went well.

**Comment by junyanz** [comment]
Thanks. Should be fixed by the latest commit.
