### ISSUE TITLE
Testing pre-trained edges2handbags model for single image inputs

### ISSUE THREAD

**Issue by azadyasar** [junyanz/pytorch-CycleGAN-and-pix2pix#466]
I'm trying to test single input images (e.g., handbag sketches) for edges2handbags dataset rather than paired images. I'm using the command provided here pytorch-CycleGAN-and-pix2pix/scripts/test_single.sh. But I'm getting the following error:
dataset [SingleImageDataset] was created
initialize network with normal
model [TestModel] was created
loading the model from ./checkpoints/edges2handbags/latest_net_G.pth
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    model.setup(opt)
  File "/home/ay/Documents/workspaces/py_ws/.virtualenvs/pytorch/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 43, in setup
    self.load_networks(opt.epoch)
  File "/home/ay/Documents/workspaces/py_ws/.virtualenvs/pytorch/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 135, in load_networks
    self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))
  File "/home/ay/Documents/workspaces/py_ws/.virtualenvs/pytorch/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 115, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/ay/Documents/workspaces/py_ws/.virtualenvs/pytorch/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 115, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/ay/Documents/workspaces/py_ws/.virtualenvs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'model'

I tried to come up with a workaround for this by concatenating a white image next to my sketches but it seems that output depends on the provided real image. or am I missing something?

Some of the my tests:

![testalan](https://user-images.githubusercontent.com/17112657/49685957-62248d80-fafe-11e8-8596-7070c9173545.png)
![testalan_fake_b](https://user-images.githubusercontent.com/17112657/49685959-6650ab00-fafe-11e8-9ab1-9fc0f2acbc7a.png)
![testalan](https://user-images.githubusercontent.com/17112657/49685991-be87ad00-fafe-11e8-81ac-f293ee984a54.png)
![testalan_fake_b](https://user-images.githubusercontent.com/17112657/49685992-c0ea0700-fafe-11e8-88c2-fba2176a8355.png)

**Comment by junyanz** [comment]
If you would like to apply a pre-trained model to a collection of input images (rather than image pairs), please use `--model test` option. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-pix2pix) for more details.
pix2pix with dropout will give you different results during test time. But the results should not depend on the real images. Also, for edges2photos application, you may want to preprocess the input before you feed it to the network. See [here](https://github.com/phillipi/pix2pix#extracting-edges) for more details.

**Comment by azadyasar** [comment]
Thank you for your answer @junyanz . As I said in the post, I've actually tried to run and test the pre-trained pix2pix model (edges2handbags) with the `--model test` option. But unfortunately I'm getting the following error.

`loading the model from ./checkpoints/edges2handbags/latest_net_G.pth
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    model.setup(opt)
  File "/home/ay/Documents/workspaces/py_ws/.virtualenvs/pytorch/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 43, in setup
    self.load_networks(opt.epoch)
  File "/home/ay/Documents/workspaces/py_ws/.virtualenvs/pytorch/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 135, in load_networks
    self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))
  File "/home/ay/Documents/workspaces/py_ws/.virtualenvs/pytorch/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 115, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/ay/Documents/workspaces/py_ws/.virtualenvs/pytorch/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 115, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/ay/Documents/workspaces/py_ws/.virtualenvs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'model'
`

I have not thought clearly. You are right the reason for getting different output images might be that instead of the change in real image pairings.

**Comment by junyanz** [comment]
For your errors, which PyTorch version are you using?

**Comment by azadyasar** [comment]
@junyanz I am using PyTorch 0.4.1

**Comment by yanjing1988** [comment]
@junyanz @azadyasar Have you solved this problem?I have the same problem as you. my pytorch is 1.0.0

**Comment by azadyasar** [comment]
@yanjing1988 I left it as it was. I am not quite sure what the reason was actually. But I've realized that the generated image does depend on the input pair as it can be seen from the figures. One thing that helped me quiet a bit was that I have tried to use the marker as thin as possible within the drawing application. Try playing with that, it might have an affect.

**Comment by junyanz** [comment]
The pix2pix output is stochastic due to dropout. 
@yanjing1988  could you tell us your command and cuda version?

**Comment by rinkstiekema** [comment]
I have the same issue as @azadyasar had:
`AttributeError: 'Sequential' object has no attribute 'model'`

I'm trying to apply my trained model in a production environment, where I just feed it a single image. I'm running the following command:
`python test.py --dataroot <data-root> --name aaai --model test --direction AtoB --dataset_mode single --norm batch --checkpoints_dir <data-root> --load_size 1024 --crop_size 1024 --no_dropout`

I've trained a pix2pix model succesfully, and testing it on a test set works properly.
Am using pytorch version 1.0.0 and the latest version of the repository. 

The full error is as follows:
```
loading the model from /var/scratch/rsa680/datasets/checkpoints/aaai/latest_net_G.pth
Traceback (most recent call last):
  File "test.py", line 47, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/home/rsa680/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 89, in setup
    self.load_networks(load_suffix)
  File "/home/rsa680/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 198, in load_networks
    self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))
  File "/home/rsa680/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 174, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/rsa680/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 174, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/var/scratch/rsa680/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'model'
```

**Comment by junyanz** [comment]
@SsnL  You mentioned you have tested it on a test set but didn't work on a single image. What's the difference? Could you give us more details regarding the CUDA/Pytorch environment?

**Comment by daniel-karl** [comment]
Same issue:
`AttributeError: 'Sequential' object has no attribute 'model'`

when setting `--model test`

**Comment by junyanz** [comment]
This [post](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/358) might be relevant. I recommend that you specify the netG and norm layers (e.g., `-netG unet --norm batch`).

**Comment by BEpresent** [comment]
Same problem here, I want to apply pix2pix in single image mode, i.e. translating an image from domain A to domain B.

` python test.py --dataroot ./datasets/custom_dataset --name custom_dataset --model test --direction AtoB --dataset_mode single --netG resnet_9blocks  --norm instance --no_dropout
`


`Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/be/Sync/PTx/Python_PTx/generative_models.py", line 57, in <module>
    model_pix2pix.setup(opt)  # regular setup: load and print networks; create schedulers
  File "path/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "path/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 197, in load_networks
    self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))
  File "path/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 173, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "path/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 173, in __patch_instance_norm_state_dict
    self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/be/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'model'`


I have seen https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/913 and https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/466 , may be I have overlooked something? Could I alternatively use pairwise data with a placeholder image to predict something?

Setting --model test seems to cause the problem.

**Comment by junyanz** [comment]
You can use placeholder images. But your error might not be related to `--dataset_mode`. I wonder if you used the same flags `--netG resnet_9blocks --norm instance --no_dropout` during training.

**Comment by BEpresent** [comment]
In the BaseOptions the default for --netG is set to 'resnet_9blocks'. As I did not change this, I assumed this is what was used. Is this correct for pix2pix too? In fact, these parameters were used during training:  --model pix2pix --gan_mode lsgan --direction AtoB\n (and a custom name), the remaining parameters therefore should take the default values, is this correct?

**Comment by junyanz** [comment]
The default parameters for different `--model` might be different. The default generator for `--model pix2pix` is `unet256`. It is overwritten in this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/pix2pix_model.py#L32).

**Comment by BEpresent** [comment]
Thank you, indeed this was the problem! For some reason, this was not clear to me. May be this could be added to the readme for others who might struggle with the testing phase of pix2pix (but it may be just me, then never mind).

**Comment by junyanz** [comment]
We mentioned it in the [Q & A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#runtimeerror-errors-in-loading-state_dict-812-671461-296). I can add more details.
