### ISSUE TITLE
How to show images with different sizes using visdom?

### ISSUE THREAD

**Issue by happsky** [junyanz/pytorch-CycleGAN-and-pix2pix#531]
I would like to use visdom to show the results during training, however, how I can show images with different sizes, such as 256X256 (input images) and 128X128 (intermediate results) at the same time.
When I am trying to show 256X256 and 128X128 images in one visdom screen, I got these error as follows:

> Traceback (most recent call last):
  File "/home/csdept/projects/train.py", line 36, in <module>
    visualizer.display_current_results(model.get_current_visuals(), epoch, save_result)
  File "/home/csdept/projects/util/visualizer.py", line 100, in display_current_results
    padding=2, opts=dict(title=title + ' images'))
  File "/home/csdept/anaconda3/envs/py3/lib/python3.7/site-packages/visdom/__init__.py", line 335, in wrapped_f
    return f(*args, **kwargs)
  File "/home/csdept/anaconda3/envs/py3/lib/python3.7/site-packages/visdom/__init__.py", line 333, in <genexpr>
    args = (_to_numpy(arg) for arg in args)
  File "/home/csdept/anaconda3/envs/py3/lib/python3.7/site-packages/visdom/__init__.py", line 312, in _to_numpy
    return np.array(a)
ValueError: could not broadcast input array from shape (3,128,128) into shape (3)

**Comment by junyanz** [comment]
Maybe setting `--display_ncols -1` can work. It will display images in different panels.

**Comment by happsky** [comment]
Thanks, it works.
