### ISSUE TITLE
batch_hed.py Unable to create correctly shaped tuple error

### ISSUE THREAD

**Issue by 3DTOPO** [junyanz/pytorch-CycleGAN-and-pix2pix#560]
After much work, I got HED working. But the batch_hed.py script is giving me this error:
`ValueError: Unable to create correctly shaped tuple from ((128, 128), (128, 128), (0, 0))`

I am trying to solve it myself, but I haven't used numpy before, so I am a bit lost. Any help would be greatly appreciated! Using Python 2.7.

Here is the for trace:
`processing image 0/40127`
`Traceback (most recent call last):`
`  File "batch_hed.py", line 63, in <module>`
`    in_ = np.pad(in_, ((border, border), (border, border), (0, 0)), 'reflect')`
`  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/arraypad.py", line 1301, in pad`
`    pad_width = _validate_lengths(narray, pad_width)`
`  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/arraypad.py", line 1080, in _validate_lengths`
`    normshp = _normalize_shape(narray, number_elements)`
`  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/arraypad.py", line 1039, in _normalize_shape`
`    raise ValueError(fmt % (shape,))`
`ValueError: Unable to create correctly shaped tuple from ((128, 128), (128, 128), (0, 0))`

**Comment by 3DTOPO** [comment]
Apparently, the error is caused by images that aren't in RGB color space.
