### ISSUE TITLE
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 4 and 5 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:83

### ISSUE THREAD

**Issue by HJLYU0519** [junyanz/pytorch-CycleGAN-and-pix2pix#566]
I used unet_256 to train pix2pix model.
I also applied 'scale_width_and_crop', 'load_size=1024' and 'crop_size=360' configuration.
Then there was a issue:
  File "/home/hongjin/PycharmProjects/CycleGAN-20190306/models/networks.py", line 541, in forward
    return torch.cat([x, self.model(x)], 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 4 and 5 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:83

Could you tell me how to solve this problem?
Thanks for your help in advance

**Comment by HJLYU0519** [comment]
And when I use ResNet, there was not this kind of issue

**Comment by taesungp** [comment]
unet_256 is only supposed to work with image size of 256, and possibly multiples of 256. Unet consists of series of downsampling and upsampling procedures, and there is size mismatch between the input and output image. 

In detail, the size of Conv2d(kernel_size=4, stride=2, padding=2) -> ConvTransposed2d(kernel_size=4, stride=2, padding=2) is not always equal to the original input image. Therefore, with UNet, you cannot use image size 360.

**Comment by tanayag** [comment]
Training Cycle Gans
Same thing, I am using unet_128, I tried using it with `256 crop size` and `128 crop size` both shows the error `RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 36 and 37 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71`

and with resnet_6blocks I get:
```
RuntimeError: CUDA out of memory. Tried to allocate 88.00 MiB (GPU 0; 11.75 GiB total capacity; 10.57 GiB already allocated; 34.50 MiB free; 71.22 MiB cached)
```

while using resnet_6blocks, I use the crop_size of, with my 12 GB GPU, it should work right?

Complete Traceback:

```
(base) tanay_curl@curlbeast128:~/pytorch-CycleGAN-and-pix2pix$ python train.py --dataroot ../data --crop_size 256 --netG resnet_6blocks --load_size 1000 --preprocess none --batch_size 1 --netD n_layers --n_layers_D 3
----------------- Options ---------------
               batch_size: 1                             
                    beta1: 0.5                           
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                crop_size: 256                           
                 dataroot: ../data                       	[default: None]
             dataset_mode: unaligned                     
                direction: AtoB                          
              display_env: main                          
             display_freq: 400                           
               display_id: 1                             
            display_ncols: 4                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                           
                    epoch: latest                        
              epoch_count: 1                             
                 gan_mode: lsgan                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: True                          	[default: None]
                 lambda_A: 10.0                          
                 lambda_B: 10.0                          
          lambda_identity: 0.5                           
                load_iter: 0                             	[default: 0]
                load_size: 1000                          	[default: 286]
                       lr: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: linear                        
         max_dataset_size: inf                           
                    model: cycle_gan                     
               n_layers_D: 3                             
                     name: experiment_name               
                      ndf: 64                            
                     netD: n_layers                      	[default: basic]
                     netG: resnet_6blocks                	[default: resnet_9blocks]
                      ngf: 64                            
                    niter: 100                           
              niter_decay: 100                           
               no_dropout: True                          
                  no_flip: False                         
                  no_html: False                         
                     norm: instance                      
              num_threads: 4                             
                output_nc: 3                             
                    phase: train                         
                pool_size: 50                            
               preprocess: none                          	[default: resize_and_crop]
               print_freq: 100                           
             save_by_iter: False                         
          save_epoch_freq: 5                             
         save_latest_freq: 5000                          
           serial_batches: False                         
                   suffix:                               
         update_html_freq: 1000                          
                  verbose: False                         
----------------- End -------------------
dataset [UnalignedDataset] was created
The number of training images = 352
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
model [CycleGANModel] was created
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 7.838 M
[Network G_B] Total number of parameters : 7.838 M
[Network D_A] Total number of parameters : 2.765 M
[Network D_B] Total number of parameters : 2.765 M
-----------------------------------------------
WARNING:root:Setting up a new session...
create web directory ./checkpoints/experiment_name/web...
The image size needs to be a multiple of 4. The loaded image size was (2550, 3301), so it was adjusted to (2552, 3300). This adjustment will be done to all images whose sizes are not multiples of 4
The image size needs to be a multiple of 4. The loaded image size was (2481, 3508), so it was adjusted to (2480, 3508). This adjustment will be done to all images whose sizes are not multiples of 4
The image size needs to be a multiple of 4. The loaded image size was (2481, 3509), so it was adjusted to (2480, 3508). This adjustment will be done to all images whose sizes are not multiples of 4
The image size needs to be a multiple of 4. The loaded image size was (2481, 3508), so it was adjusted to (2480, 3508). This adjustment will be done to all images whose sizes are not multiples of 4
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/home/tanay_curl/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 183, in optimize_parameters
    self.forward()      # compute fake images and reconstruction images.
  File "/home/tanay_curl/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 115, in forward
    self.rec_A = self.netG_B(self.fake_B)   # G_B(G_A(A))
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tanay_curl/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 373, in forward
    return self.model(input)
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tanay_curl/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 432, in forward
    out = x + self.conv_block(x)  # add skip connections
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/instancenorm.py", line 55, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/tanay_curl/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1713, in instance_norm
    use_input_stats, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 88.00 MiB (GPU 0; 11.75 GiB total capacity; 10.57 GiB already allocated; 34.50 MiB free; 71.22 MiB cached)

```

**Comment by junyanz** [comment]
Your current setting is different from what you have described. Given the logging information, your setting is `preprocess none --load_size 1000 --crop_size 256`.

Try to change it to `preprocess resize_and_crop --load_size 286 --crop_size 256`.

**Comment by tanayag** [comment]
Yeah, its working now, even with `--load_size 1024`, I thought giving `--load_size` and `--crop_size` arguments would overwrite the `--preprocess` argument!
Thanks for the quick reply!
