### ISSUE TITLE
ValueError: empty range for randrange() but large images

### ISSUE THREAD

**Issue by vict0rsch** [junyanz/pytorch-CycleGAN-and-pix2pix#568]
I've explored issues tips and Q&As but can't get my head around this error. I use `--preprocess scale_width_and_crop` with default parameters (`load_size=286`, `crop_size=256`) but still get this error in spite of all my images having both `height` and `width` larger than 300px and `--display_id 0` for the training of a `cycle_gan` model

```
create web directory ./checkpoints/flood_cg_aug_v2_2/web...
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/network/home/schmidtv/ccai/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/network/home/schmidtv/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/network/home/schmidtv/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/network/home/schmidtv/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/network/home/schmidtv/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/network/home/schmidtv/ccai/pytorch-CycleGAN-and-pix2pix/data/unaligned_dataset.py", line 60, in __getitem__
    A = self.transform_A(A_img)
  File "/network/home/schmidtv/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/network/home/schmidtv/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 421, in __call__
    i, j, h, w = self.get_params(img, self.size)
  File "/network/home/schmidtv/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 399, in get_params
    i = random.randint(0, h - th)
  File "/network/home/schmidtv/anaconda3/envs/cyclePT/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/network/home/schmidtv/anaconda3/envs/cyclePT/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-41, -41)
```

**Comment by taesungp** [comment]
Not sure what went wrong here. The error is probably inside torchvision.transforms.RandomCrop. You might wanna print the image size and the intended cropping size right before the error occurs.

**Comment by amrbenattia** [comment]
@Vict0rSch 
Did you solve your problem ?

**Comment by junyanz** [comment]
What might have happened is that: you have an image with (width, height) = (3000, 1500). 
After resizing using `--load_size 286 --preprocess scale_width_and_crop`. The image size will be (256, 128). Cropping it using `--crop_size 256` will produce a randrange error.

**Comment by Vict0rSch** [comment]
hmmm and what do you advise @junyanz ? 
(so, no @amrbenattia :( )

**Comment by junyanz** [comment]
I recommend that you try a different `--preprocess` option (e.g., `resize_and_crop`)

**Comment by Vahe987** [comment]
hi @vict0rsch , I just had the same issue :)), solved 
basically in the "base_options.py" file the '--crop_size' was bigger number than '--load_size', forgot to change back after testing
I guess will be better if this parameter go to "test_options.py", will avoid confusion
