### ISSUE TITLE
Error when training with input_nc=1 or output_nc=1

### ISSUE THREAD

**Issue by k-fujimt** [junyanz/pytorch-CycleGAN-and-pix2pix#581]
Hi.
I'm trying to use pix2pix for grayscale-image-to-grayscale-image translation.
So I set as `--input_nc 1 --output_nc 1` but I got following error:

```
----------------- Options ---------------
               batch_size: 32                            	[default: 1]
                    beta1: 0.5                           
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                crop_size: 256                           
                 dataroot: ./datasets/dataset_1	[default: None]
             dataset_mode: aligned                       
                direction: BtoA                          	[default: AtoB]
              display_env: main                          
             display_freq: 400                           
               display_id: 0                             	[default: 1]
            display_ncols: 4                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                           
                    epoch: latest                        
              epoch_count: 1                             
                 gan_mode: vanilla                       
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 1                             	[default: 3]
                  isTrain: True                          	[default: None]
                lambda_L1: 100.0                         
                load_iter: 0                             	[default: 0]
                load_size: 256                           	[default: 286]
                       lr: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: linear                        
         max_dataset_size: inf                           
                    model: pix2pix                       	[default: cycle_gan]
               n_layers_D: 3                             
                     name: experiment_name               
                      ndf: 64                            
                     netD: basic                         
                     netG: unet_256                      
                      ngf: 64                            
                    niter: 500                           	[default: 100]
              niter_decay: 0                             	[default: 100]
               no_dropout: False                         
                  no_flip: False                         
                  no_html: False                         
                     norm: batch                         
              num_threads: 4                             
                output_nc: 1                             	[default: 3]
                    phase: train                         
                pool_size: 0                             
               preprocess: resize_and_crop               
               print_freq: 100                           
             save_by_iter: False                         
          save_epoch_freq: 1                             	[default: 5]
         save_latest_freq: 5000                          
           serial_batches: False                         
                   suffix:                               
         update_html_freq: 1000                          
                  verbose: False                         
----------------- End -------------------
dataset [AlignedDataset] was created
The number of training images = 8000
initialize network with normal
initialize network with normal
model [Pix2PixModel] was created
---------- Networks initialized -------------
[Network G] Total number of parameters : 54.408 M
[Network D] Total number of parameters : 2.765 M
-----------------------------------------------
create web directory ./checkpoints/experiment_name/web...
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/src/workspace/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/src/workspace/pytorch-CycleGAN-and-pix2pix/data/aligned_dataset.py", line 55, in __getitem__
    A = A_transform(A)
  File "/opt/conda/lib/python3.5/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/opt/conda/lib/python3.5/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/opt/conda/lib/python3.5/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]
```

When I try `--input_nc 3 --output_nc 3`, it worked fine and no errors occured.
When I try `--input_nc 3 --output_nc 1` and `--input_nc 1 --output_nc 3`, the same error occured.

I have tried the same task few months ago, but then no errors occured. 
So the errors may be caused by recent updates.
Of course, the cause may be my mistake or my environment.

Do you know any solutions?

**Comment by k-fujimt** [comment]
I found that this error happens when I follow your tutorial, too.
I cloned latest version of this repository and tried `python train.py --display_id -1 --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA` and it worked fine.
But when I added `--input_nc 1` or `--output_nc 1` or both of them, following error happens:

```
$ python train.py --display_id -1  --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA --output_nc 1----------------- Options ---------------
               batch_size: 1                             
                    beta1: 0.5                           
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                crop_size: 256                           
                 dataroot: ./datasets/facades            	[default: None]
             dataset_mode: aligned                       
                direction: BtoA                          	[default: AtoB]
              display_env: main                          
             display_freq: 400                           
               display_id: -1                            	[default: 1]
            display_ncols: 4                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                           
                    epoch: latest                        
              epoch_count: 1                             
                 gan_mode: vanilla                       
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: True                          	[default: None]
                lambda_L1: 100.0                         
                load_iter: 0                             	[default: 0]
                load_size: 286                           
                       lr: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: linear                        
         max_dataset_size: inf                           
                    model: pix2pix                       	[default: cycle_gan]
               n_layers_D: 3                             
                     name: facades_pix2pix               	[default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: unet_256                      
                      ngf: 64                            
                    niter: 100                           
              niter_decay: 100                           
               no_dropout: False                         
                  no_flip: False                         
                  no_html: False                         
                     norm: batch                         
              num_threads: 4                             
                output_nc: 1                             	[default: 3]
                    phase: train                         
                pool_size: 0                             
               preprocess: resize_and_crop               
               print_freq: 100                           
             save_by_iter: False                         
          save_epoch_freq: 5                             
         save_latest_freq: 5000                          
           serial_batches: False                         
                   suffix:                               
         update_html_freq: 1000                          
                  verbose: False                         
----------------- End -------------------
dataset [AlignedDataset] was created
The number of training images = 400
initialize network with normal
initialize network with normal
model [Pix2PixModel] was created
---------- Networks initialized -------------
[Network G] Total number of parameters : 54.410 M
[Network D] Total number of parameters : 2.767 M
-----------------------------------------------
create web directory ./checkpoints/facades_pix2pix/web...
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/src/workspace/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/src/workspace/pytorch-CycleGAN-and-pix2pix/data/aligned_dataset.py", line 55, in __getitem__
    A = A_transform(A)
  File "/opt/conda/lib/python3.5/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/opt/conda/lib/python3.5/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/opt/conda/lib/python3.5/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

```

Why do I take such error when setting input or output channels to 1 ?
Do you have any solutions ?

**Comment by k-fujimt** [comment]
I found that this error happens when I follow your tutorial, too.
I cloned latest version of this repository and tried `python train.py --display_id -1 --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA` and it worked fine.
But when I added `--input_nc 1` or `--output_nc 1` or both of them, following error happens:

```
$ python train.py --display_id -1  --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA --output_nc 1----------------- Options ---------------
               batch_size: 1                             
                    beta1: 0.5                           
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                crop_size: 256                           
                 dataroot: ./datasets/facades            	[default: None]
             dataset_mode: aligned                       
                direction: BtoA                          	[default: AtoB]
              display_env: main                          
             display_freq: 400                           
               display_id: -1                            	[default: 1]
            display_ncols: 4                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                           
                    epoch: latest                        
              epoch_count: 1                             
                 gan_mode: vanilla                       
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: True                          	[default: None]
                lambda_L1: 100.0                         
                load_iter: 0                             	[default: 0]
                load_size: 286                           
                       lr: 0.0002                        
           lr_decay_iters: 50                            
                lr_policy: linear                        
         max_dataset_size: inf                           
                    model: pix2pix                       	[default: cycle_gan]
               n_layers_D: 3                             
                     name: facades_pix2pix               	[default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: unet_256                      
                      ngf: 64                            
                    niter: 100                           
              niter_decay: 100                           
               no_dropout: False                         
                  no_flip: False                         
                  no_html: False                         
                     norm: batch                         
              num_threads: 4                             
                output_nc: 1                             	[default: 3]
                    phase: train                         
                pool_size: 0                             
               preprocess: resize_and_crop               
               print_freq: 100                           
             save_by_iter: False                         
          save_epoch_freq: 5                             
         save_latest_freq: 5000                          
           serial_batches: False                         
                   suffix:                               
         update_html_freq: 1000                          
                  verbose: False                         
----------------- End -------------------
dataset [AlignedDataset] was created
The number of training images = 400
initialize network with normal
initialize network with normal
model [Pix2PixModel] was created
---------- Networks initialized -------------
[Network G] Total number of parameters : 54.410 M
[Network D] Total number of parameters : 2.767 M
-----------------------------------------------
create web directory ./checkpoints/facades_pix2pix/web...
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/src/workspace/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/src/workspace/pytorch-CycleGAN-and-pix2pix/data/aligned_dataset.py", line 55, in __getitem__
    A = A_transform(A)
  File "/opt/conda/lib/python3.5/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/opt/conda/lib/python3.5/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/opt/conda/lib/python3.5/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

```

Why do I take such error when setting input or output channels to 1 ?
Do you have any solutions ?

**Comment by k-fujimt** [comment]
Somehow the error doesn't appear after I stopped using docker (not from this repository).
It seems that the cause of above error was my environment.
Thanks

**Comment by guxiao0822** [comment]
I changed line 107-108 in base_dataset.py to        
 transform_list += [transforms.ToTensor(),
                           transforms.Normalize([0.5], [0.5])]
and now it works

**Comment by k-fujimt** [comment]
@guxiao0822 Thank you very much for great suggestion!
I confirmed it was working fine after editing as you commented.

As far as my understanding, function `get_transform` in class `BaseDataset` (or subclasses of it) is called for building transformation procedure for loading images.
In this procedure, grayscale-transformation is done if `grayscale == True` (means `input_nc` or `output_nc` is 1).
So in case of grayscale, the shape of tensor is chenged from (3, height, width) to (1, height, width).
However, normalizing procedure is done for tensor with shape (3, height, width) for all cases (line 107--108) and it caused my error. 
I think better code from line 106 to line 108 of `base_dataset.py` is as follows:

```python:
if convert:
        transform_list.append(transforms.ToTensor())
        if grayscale:
            transform_list.append(transforms.Normalize([0.5], [0.5]))
        else:
            transform_list.append(transforms.Normalize((0.5, 0.5, 0.5), 
                                                        (0.5, 0.5, 0.5)))
```
