### ISSUE TITLE
Multiple GPU on pix2pix/cannot allocate memory

### ISSUE THREAD

**Issue by prmex900** [junyanz/pytorch-CycleGAN-and-pix2pix#584]
Hi! I started training with 8 GPU on pix2pix, but training process still takes a while.
It took 12 hours fo 40 epochs.
My dataset has 15k images. Is it fair or I do something wrong?
Images has small resolution. 300x200 px photos 
when I used batch size  4 it was fine but slow. when I switch to batch size 16 or 32 it ends up with this error

```
learning rate = 0.0002000
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/home/antboror/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/antboror/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "/home/antboror/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 560, in __init__
    w.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by SsnL** [comment]
You have too little memory and fork can't start a new subprocess.
