### ISSUE TITLE
pytorch=0.4 has no torch.as_tensor

### ISSUE THREAD

**Issue by otizis** [junyanz/pytorch-CycleGAN-and-pix2pix#591]
when use conda env with environment.yml, run pix2pix train/test 
get error like:
```Traceback (most recent call last):
  File "train.py", line 43, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/home/pix2pix/pytorch-pix2pix/data/__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/pix2pix/.conda/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/pix2pix/.conda/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/pix2pix/.conda/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pix2pix/.conda/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pix2pix/pytorch-pix2pix/data/aligned_dataset.py", line 55, in __getitem__
    A = A_transform(A)
  File "/home/pix2pix/.conda/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/pix2pix/.conda/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/pix2pix/.conda/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torchvision/transforms/functional.py", line 206, in normalize
    mean = torch.as_tensor(mean, dtype=torch.float32, device=tensor.device)
AttributeError: module 'torch' has no attribute 'as_tensor'
```
checked [pytorch doc](https://pytorch.org/docs/0.4.1/torch.html#torch.as_tensor)  , so looks like need update to pytorch=0.4.1

**Comment by junyanz** [comment]
Cool. Just updated the environment.yml.
