### ISSUE TITLE
set gpu_ids error

### ISSUE THREAD

**Issue by huangdl007** [junyanz/pytorch-CycleGAN-and-pix2pix#62]
when I set '--gpu_ids 1', it raised:

> Traceback (most recent call last):
  File "train.py", line 26, in <module>
    model.optimize_parameters()
  File "/data1/huangdeliang/projects/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 158, in optimize_parameters
    self.backward_G()
  File "/data1/huangdeliang/projects/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 145, in backward_G
    self.loss_cycle_A = self.criterionCycle(self.rec_A, self.real_A) * lambda_A
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/loss.py", line 24, in forward
    return backend_fn(self.size_average)(input, target)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/thnn/auto.py", line 41, in forward
    output, *self.additional_args)
RuntimeError: Assertion `THCTensor_(checkGPU)(state, 2, input, target)' failed. Some of weight/gradient/input tensors are located on different GPUs. Please move them to a single one. at /b/wheel/pytorch-src/torch/lib/THCUNN/generic/AbsCriterion.cu:13

who can tell me Why I cannot only select gpu 1? Thank you~

**Comment by junyanz** [comment]
I am aware of the bug but I haven't found a fix. For the current code, you always need to use gpu0. However, you can add flag "CUDA_VISIBLE_DEVICES=1" to specify the GPU when running the python script while setting the `gpu_ids 0`. See [here](https://discuss.pytorch.org/t/select-gpu-device-through-env-vars/318)  for more details.

**Comment by huangdl007** [comment]
@junyanz thx～～
We also can set `torch.cuda.set_device(opt.gpu_ids[0])` before the model's initialization. See [here](https://github.com/pytorch/pytorch/issues/1150) for more details.

**Comment by junyanz** [comment]
I tried the `torch.cuda.set_device(opt.gpu_ids[0])` but it didn't work for me. Let me know if you can make it work, and I can merge it through pull request.

**Comment by huangdl007** [comment]
@junyanz 
I added `torch.cuda.set_device(opt.gpu_ids[0])` in train.py, before the network initialization.
