### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'list' and 'int'?

### ISSUE THREAD

**Issue by AlexanLee** [junyanz/pytorch-CycleGAN-and-pix2pix#63]
when i run the train.py i get the error like this:
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/Users/lijianli/Rep/pytorch-CycleGAN-and-pix2pix/data/unaligned_dataset.py", line 33, in __getitem__
    A_img = self.transform(A_img)
  File "/usr/local/lib/python2.7/site-packages/torchvision/transforms.py", line 29, in __call__
    img = t(img)
  File "/usr/local/lib/python2.7/site-packages/torchvision/transforms.py", line 139, in __call__
    ow = int(self.size * w / h)
TypeError: unsupported operand type(s) for /: 'list' and 'int'

**Comment by icbcbicc** [comment]
@AlexanLee 
May be you should install the torchvision package from the source:
`git clone https://github.com/pytorch/vision
cd vision
python setup.py install`
related issue: #42

**Comment by botcs** [comment]
I work with virtualenvs, and if you install from package I believe that there were conflicts, and after I uninstalled torchvision from pip, the installation from source started to work, and it resolved this issue

**Comment by liuxiaoxinhappy** [comment]
I solved this problem with @icbcbicc 's answer. Thanks!

**Comment by Designbook1** [comment]
@icbcbicc ur answer works, thank you very much!
