### ISSUE TITLE
PackBitsDecode: Not enough data for scanline 208.

### ISSUE THREAD

**Issue by Amarintine** [junyanz/pytorch-CycleGAN-and-pix2pix#645]
PackBitsDecode: Not enough data for scanline 208.
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    for i, data in enumerate(dataset):
  File "/home/luvis/chenxu/data/__init__.py", line 84, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/luvis/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/luvis/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/luvis/chenxu/data/my_dataset.py", line 35, in __getitem__
    A = AB.crop((0, 0, w2, h))
  File "/home/luvis/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 1136, in crop
    self.load()
  File "/home/luvis/anaconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py", line 1077, in load
    return self._load_libtiff()
  File "/home/luvis/anaconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py", line 1168, in _load_libtiff
    raise IOError(err)
OSError: -2
 I have got this issue when i trained at epoch 80, what's wrong with it?

**Comment by junyanz** [comment]
It seems that you have some issues when loading a TIff image. You may want to check whether your Tiff images are corrupted or if these files still exist.

**Comment by Amarintine** [comment]
貌似这个tif图片是16位的，导致加载出错

Jun-Yan Zhu <notifications@github.com> 于2019年5月18日周六 上午2:09写道：

**Comment by Amarintine** [comment]
maybe not,cos the error was occured at epoch 80, it has gone through a whole datasets. but when i change server ,it's gone!
