### ISSUE TITLE
ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')

### ISSUE THREAD

**Issue by zyouc518** [junyanz/pytorch-CycleGAN-and-pix2pix#710]
Hello, I'm running the train.py and got the following warning; I'm using our company's server remotely. 

I'm wondering why this train file need to set up a new session. Because I thought the we just need to normally train the GAN and produce the generated graphs. And I can use sftp to download the graphs from server to my own laptop to check the graphs. 

```bash
-----------------------------------------------
WARNING:root:Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/data/home/tomkshi/python3.7.3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/data/home/tomkshi/python3.7.3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/data/home/tomkshi/python3.7.3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/data/home/tomkshi/python3.7.3/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/data/home/tomkshi/python3.7.3/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/data/home/tomkshi/python3.7.3/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/tomkshi/python3.7.3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/data/home/tomkshi/python3.7.3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/data/home/tomkshi/python3.7.3/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='100.116.79.55', port=8080): Max retries exceeded with url: http://localhost:8097/env/main (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
```

**Comment by junyanz** [comment]
The issues are related to visdom. You can disable the visdom server by setting `--display_id 0`.

**Comment by zyouc518** [comment]
Gosh... You're genius!! The code you wrote is awesome!
