### ISSUE TITLE
RuntimeError: Padding size should be less than the corresponding input dimension

### ISSUE THREAD

**Issue by benkmoore** [junyanz/pytorch-CycleGAN-and-pix2pix#749]
Hi

I'm trying to input a 3d lidar array into a generator, instead of an image. Unfortunately I'm getting a padding size/dimension error as below:

`Traceback (most recent call last):
  File "train.py", line 51, in <module>
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/home/ben/Documents/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 185, in optimize_parameters
    self.forward()      # compute fake images and reconstruction images.
  File "/home/ben/Documents/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 116, in forward
    self.fake_B = self.netG_A(self.real_A)  # G_A(A)
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ben/Documents/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 372, in forward
    return self.model(input)
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ben/Documents/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 431, in forward
    out = x + self.conv_block(x)  # add skip connections
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/modules/padding.py", line 171, in forward
    return F.pad(input, self.padding, 'reflect')
  File "/home/ben/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 2817, in pad
    ret = torch._C._nn.reflection_pad2d(input, pad)
RuntimeError: Padding size should be less than the corresponding input dimension, but got: padding (1, 1) at dimension 3 of input [1, 256, 239782, 1]
`

When I load the data from the a file location the loaded size is:
`torch.Size([3, 959125, 1])`

I then increase the size of the third dimension, using .expand() to get:
`torch.Size([3, 959125, 4])`

I then try to load the array to the generator it is of size:
`torch.Size([1, 3, 959125, 4])`

Is there any way I can adjust the padding such that I wont receive this error? If possible could you explain also why I get a dimension of 256for the second dimension where the  error occurs?

Any help/advice would be great.

Thanks!

**Comment by benkmoore** [comment]
@junyanz any ideas? Thanks

**Comment by junyanz** [comment]
The current generator and discriminator do not work for 3D data. You need to use 3D [convolutional](https://pytorch.org/docs/stable/_modules/torch/nn/modules/conv.html#Conv3d) layers for 3D data. I recommend that you implement your own networks.

**Comment by benkmoore** [comment]
Thank you @junyanz
