### ISSUE TITLE
Some strange error but training is continue.How i can solve it?Does is influence result?

### ISSUE THREAD

**Issue by Endless-Hao** [junyanz/pytorch-CycleGAN-and-pix2pix#778]
Problem blew: How I can solve it?
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fbdb1faa128>>
Traceback (most recent call last):
  File "/home/pch/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/pch/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/pch/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/connection.py", line 737, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fbdd5df8d30>>
Traceback (most recent call last):
  File "/home/pch/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/pch/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/pch/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/pch/anaconda3/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError: 
(epoch: 11, iters: 20, time: 0.364, data: 0.003) D_A: 0.062 G_A: 0.481 cycle_A: 1.802 idt_A: 0.761 D_B: 0.035 G_B: 0.792 cycle_B: 1.773 idt_B: 0.828 
(epoch: 11, iters: 120, time: 0.345, data: 0.002) D_A: 0.044 G_A: 0.905 cycle_A: 1.665 idt_A: 0.807 D_B: 0.074 G_B: 0.701 cycle_B: 1.721 idt_B: 0.783 
End of epoch 11 / 200 	 Time Taken: 45 sec
learning rate = 0.0002000

**Comment by junyanz** [comment]
I am not sure. It might be caused (1) a corrupt image file (2) Your image size is not compatible with the network. Again, pix2pix only supports 256x256 input.

**Comment by Endless-Hao** [comment]
@junyanz I use my own dataload.py, transfer them to set_input, my data was 256*256 without the path. Below was changed cycle_gan_model.py set_input:
    def set_input(self, inputa,inputb):
        """Unpack input data from the dataloader and perform necessary pre-processing steps.
        Parameters:
            input (dict): include the data itself and its metadata information.
        The option 'direction' can be used to swap domain A and domain B.
        """
        AtoB = self.opt.direction == 'AtoB'
        # self.real_A = input['A' if AtoB else 'B'].to(self.device)
        # self.real_B = input['B' if AtoB else 'A'].to(self.device)
        # self.image_paths = input['A_paths' if AtoB else 'B_paths']
        self.real_A = inputa['image'].to(self.device)
        # print(inputa['image'].shape)
        self.real_B = inputb['image'].to(self.device)

**Comment by Endless-Hao** [comment]
@junyanz I can finish training, I try epoch200.

**Comment by Endless-Hao** [comment]
@junyanz Hi i found my data, the sum of domain A(after bs) and domain B(after bs)was different.
len(dataa)=128  len(datab)=172,i use blew.
        for data1,data2 in zip(dataa,datab):  # inner loop within one epoch
            iter_start_time = time.time()  # timer for computation per iteration
            if total_iters % opt.print_freq == 0:
                t_data = iter_start_time - iter_data_time
            visualizer.reset()
            total_iters += opt.batch_size
            epoch_iter += opt.batch_size
            # data1=next(a_iter)
            # data2=next(b_iter)
            model.set_input(data1,data2)   
Maybe is this problem.But How can i use different sum A and B to train.

**Comment by Endless-Hao** [comment]
@junyanz I try the same sum of dataa and datab ,it was no error. How i can fix it to use the different sum of dataa and datab.Do you have some advice? thank you

**Comment by junyanz** [comment]
Your FOR loop only works when A and B have the same number of images. Please look at unaligned_dataset [dataloader](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py). See this [line](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/data/unaligned_dataset.py#L52).

**Comment by Endless-Hao** [comment]
@junyanz I solve it. Thank you!
