### ISSUE TITLE
OSRrror

### ISSUE THREAD

**Issue by yuxinzhang3** [junyanz/pytorch-CycleGAN-and-pix2pix#876]
two OSError
OSError: image file is truncated         OSError: Caught OSError in DataLoader worker process 3
File "train.py", line 44, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/root/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/root/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
Original Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/PIL/ImageFile.py", line 234, in load
    s = read(self.decodermaxblock)
  File "/root/anaconda3/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 658, in load_read
    cid, pos, length = self.png.read()
  File "/root/anaconda3/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 122, in read
    length = i32(s)
  File "/root/anaconda3/lib/python3.7/site-packages/PIL/_binary.py", line 81, in i32be
    return unpack_from(">I", c, o)[0]

**Comment by junyanz** [comment]
Your image files might be corrupted. You can print the image path and see which image has caused the issue.
