### ISSUE TITLE
About Error

### ISSUE THREAD

**Issue by hanatyaki6** [junyanz/pytorch-CycleGAN-and-pix2pix#899]
Hi!
I am in trouble because I got an error and could not solve it.
Please tell me how to resolve.

The details of the error are described below.
Error during test.

Traceback (most recent call last):
  File "test.py", line 60, in <module>
    model.test()           # run inference
  File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\base_model.py", line 105, in test
    self.forward()
  File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\pix2pix_model.py", line 88, in forward
    self.fake_B = self.netG(self.real_A)  # G(A)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 465, in forward
    return self.model(input)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 533, in forward
    return self.model(x)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
    return torch.cat([x, self.model(x)], 1)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
    return torch.cat([x, self.model(x)], 1)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
    return torch.cat([x, self.model(x)], 1)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
    return torch.cat([x, self.model(x)], 1)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
    return torch.cat([x, self.model(x)], 1)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
    return torch.cat([x, self.model(x)], 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 14 and 15 in dimension 3 at C:/w/1/s/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu:71

**Comment by hanatyaki6** [comment]
> 
> 
> Hi!
> I am in trouble because I got an error and could not solve it.
> Please tell me how to resolve.
> 
> The details of the error are described below.
> Error during test.
> 
> Traceback (most recent call last):
> File "test.py", line 60, in
> model.test() # run inference
> File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\base_model.py", line 105, in test
> self.forward()
> File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\pix2pix_model.py", line 88, in forward
> self.fake_B = self.netG(self.real_A) # G(A)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
> return self.module(*inputs[0], **kwargs[0])
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 465, in forward
> return self.model(input)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 533, in forward
> return self.model(x)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
> return torch.cat([x, self.model(x)], 1)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
> return torch.cat([x, self.model(x)], 1)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
> return torch.cat([x, self.model(x)], 1)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
> return torch.cat([x, self.model(x)], 1)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
> return torch.cat([x, self.model(x)], 1)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\migita\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\migita\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 535, in forward
> return torch.cat([x, self.model(x)], 1)
> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 14 and 15 in dimension 3 at C:/w/1/s/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu:71
