### ISSUE TITLE
Using imgs with nc=1

### ISSUE THREAD

**Issue by Eulsen** [junyanz/pytorch-CycleGAN-and-pix2pix#90]
Hey!
Thanks for sharing this great code!
The code workes nicely with nc=3 images

But now I want to use the code with imgs that have nc=1. (I checked that the images have 8bit)

I use the command:  python train.py --dataroot ./datasets/pic2seg2 --name amneo_cyclegan --model cycle_gan --no_dropout --loadSize 512 --fineSize 512 --input_nc 1 --output_nc 1

but I get the following error:

model [CycleGANModel] was created
create web directory ./checkpoints\a1_cycle\web...
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    model.optimize_parameters()
  File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\cycle_gan_model.py", line 159, in optimize_parameters
    self.backward_G()
  File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\cycle_gan_model.py", line 137, in backward_G
    self.fake_B = self.netG_A.forward(self.real_A)
  File "C:\Users\Eulsen\Documents\Programs\Python\pytorch-CycleGAN-and-pix2pix\models\networks.py", line 175, in forward
    return nn.parallel.data_parallel(self.model, input, self.gpu_ids)
  File "C:\Users\Eulsen\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 103, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "C:\Users\Eulsen\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Eulsen\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 64, in forward
    input = module(input)
  File "C:\Users\Eulsen\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Eulsen\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "C:\Users\Eulsen\Anaconda3\lib\site-packages\torch\nn\functional.py", line 43, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_BAD_PARAM

What am I missing here? Can someone help me?

Help would be much appreciated!

**Comment by junyanz** [comment]
`nc=1` is currently not well supported. I will look at it later if you I have time in the following week.

**Comment by Eulsen** [comment]
That would be great!! It would allow me to process larger pictures.
Thank you!!!

Btw. it seems that that pytorch implementations in general need a lot more gpu ram than 
for example Tensorflow implementations of the same problem.
Is this a special feature of pytorch or is this generic for torch implementations?

**Comment by junyanz** [comment]
`input_nc=1` is being supported now.
