### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by ZangChaoyu** [junyanz/pytorch-CycleGAN-and-pix2pix#900]
E:\Anaconda\python.exe E:/Pycharm_Code/Fruit_count/train.py
Traceback (most recent call last):
  File "E:/Pycharm_Code/Fruit_count/train.py", line 17, in <module>
    torch.cuda.set_device(gpus[0])
  File "E:\Anaconda\lib\site-packages\torch\cuda\__init__.py", line 293, in set_device
    torch._C._cuda_setDevice(-1)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by junyanz** [comment]
See #360.
