### ISSUE TITLE
ValueError: trying to resize HD images

### ISSUE THREAD

**Issue by BanjerHD** [junyanz/pytorch-CycleGAN-and-pix2pix#966]
Hello,
I am trying to train with high resolution images (some are 16:9 some 1:1 and some 16:10), I ran into an `CUDA Error: Out of Memory`. So I read the [docs](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#preprocessing) and came to the conclusion that I had to do some cropping and resizing. What is the best way to do this so I get the best results when deploying this on real high resolution images?
I tried: `--preproces scale_width --crop_size 256`, `--preproces scale_width_and_crop --load_size 286 --crop_size 256` and `--preproces scale_width_and_crop --load_size 256 --crop_size 256`

The first one gives this error right after starting (after create web directory...):
```
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/content/drive/My Drive/CycleGAN_data/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 374 and 340 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:612
```

and the last two give this error (also just after starting):
```
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/content/drive/My Drive/CycleGAN_data/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 90, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/CycleGAN_data/pytorch-CycleGAN-and-pix2pix/data/unaligned_dataset.py", line 60, in __getitem__
    A = self.transform_A(A_img)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 483, in __call__
    i, j, h, w = self.get_params(img, self.size)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 461, in get_params
    i = random.randint(0, h - th)
  File "/usr/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-81, -81)
```

How can I solve this?

Thanks for helping!

**Comment by junyanz** [comment]
You may want to increase your `--load_size`. This error happened when the shorter side of your resized image is smaller than `--fine_size`.  We plan to improve the implementation in the future, by giving you a warning if it happens.
