### ISSUE TITLE
AttributeError: 'module' object has no attribute 'InstanceNorm2d'

### ISSUE THREAD

**Issue by wlwsea** [junyanz/pytorch-CycleGAN-and-pix2pix#99]
Hello @junyanz @taesung89 @phillipi @andyli @alanyee ,

When I use the following command, 
`python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --no_dropout`
It showed the following error. What's the reason of that? And how can i solve this problem?
Thanks a ton!

`Traceback (most recent call last):
  File "train.py", line 13, in <module> model = create_model(opt)
  File "/wlwsea/pytorch-CycleGAN-and-pix2pix-master/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/wlwsea/pytorch-CycleGAN-and-pix2pix-master/models/cycle_gan_model.py", line 31, in initialize
    opt.ngf, opt.which_model_netG, opt.norm, not opt.no_dropout, self.gpu_ids)
  File "/wlwsea/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 38, in define_G
    norm_layer = get_norm_layer(norm_type=norm)
  File "/wlwsea/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 29, in get_norm_layer
    norm_layer = functools.partial(nn.InstanceNorm2d, affine=False)
AttributeError: 'module' object has no attribute 'InstanceNorm2d'
Traceback (most recent call last):
  File "train.py", line 13, in <module> model = create_model(opt)
  File "/wlwsea/pytorch-CycleGAN-and-pix2pix-master/models/models.py", line 19, in create_model
    model.initialize(opt)
  File "/wlwsea/pytorch-CycleGAN-and-pix2pix-master/models/cycle_gan_model.py", line 31, in initialize
    opt.ngf, opt.which_model_netG, opt.norm, not opt.no_dropout, self.gpu_ids)
  File "/wlwsea/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 38, in define_G
    norm_layer = get_norm_layer(norm_type=norm)
  File "/wlwsea/pytorch-CycleGAN-and-pix2pix-master/models/networks.py", line 29, in get_norm_layer
    norm_layer = functools.partial(nn.InstanceNorm2d, affine=False)
AttributeError: 'module' object has no attribute 'InstanceNorm2d'
`

**Comment by wlwsea** [comment]
Anyone can help me? I'm really confused about this problem.
Thanks a ton!

**Comment by PraveerSINGH** [comment]
@wlwsea : I am having similar issue. How did you manage to solve this ?

**Comment by wlwsea** [comment]
@PraveerSINGH : 
I just re-install PyTorch in my computer, and it didn't show that error again.
Reference:  [http://pytorch.org/](url)
